### ISSUE TITLE
Coherent way to fail/abort data import of really large datasets

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1048]
# Context

There is a performance limitation in terms of a dataset size that can be imported into Lumen.

When you try to import a really large dataset as a csv file, Lumen produces an error. The error is quite generic, so a user would not guess why import failed.

When you try to import a really large dataset via Flow API, the datasets keep loading forever. There is no way to kill the dataset from the user interface. I believe, one needs to restart the app and then kill import job from the dataset.

# Problem or idea

It is unclear to a user why a csv import of a dataset fails, or why Flow import keeps perpetually loading.
I think there should be a coherent and a more user-friendlier way to deal with import jobs that Lumen cannot handle.
@peeb suggested we add some functions to the admin area.
@Kiarii perhaps you have some ideas as well, from the UX point of view? 

# Solution or next step
How could we solve it?

**Comment by Kiarii** [comment]
one option for the import step: check data size before import; if size > allowed size: do not initiate import, show error e.g. "selected dataset is too large. maximum size supported is xx Gigabytes". The alternative being that we let the user go via the whole import process and only afterwards notify them of its failure and reason.

checking dataset size shd be doable at least for file-sourced (csv, xls) datasets. For flow, maybe the import API shd determine size in order to determine whether its within allowed limits. Am not sure how size checking would work for datasets whose source is a link 

we need to identify the following details to define the workflow concretely:
1. allowed dataset size
2. whether size checking happens before import is initiated
3. whether lumen disallows the import of large datasets automagically and gives the reason or the user has to cancel them manually
4. whether we want to have a [cancel import] or the like for a dataset whose import has already commenced
5. Lastly but not least, we ought to tell the user how to in any case import larger than allowed datasets: e.g. do they split the dataset, import the splits and merge them in Lumen, or..
