### ISSUE TITLE
The use of count aggregation in bar chart

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1055]
# Context
Yesterday we had a chat with @gabemart about it and the conclusion was that count aggregation in bar charts is a bit problematic.

# Problem or idea
The count aggregation counts values of the column from the X axis, which makes the Y axis scale redundant.

Bar chart example: https://lumen.akvotest.org/visualisation/59b00ddf-3abd-4057-9926-dc5a7cbdc1be

As you can see, with aggregation set to count, nothing changes as you switch between different columns in the Y axis

**Comment by jonase** [comment]
I've also noticed the same issue (see https://github.com/akvo/akvo-lumen/issues/1016#issuecomment-325651526)

I think `count` aggregation is the most common one and should probably be the default

**Comment by finnfiddle** [comment]
@nadiagorchakova this seems like its working as expected. what should I do?

**Comment by nadiagorchakova** [comment]
Hi @finnfiddle, I believe the issue hasn't been resolved yet.
The issue is that when count aggregation is used, the y axis becomes redundant as Lumen counts on X axis 'buckets'. I tried to show it in this gif

![ezgif com-gif-maker 9](https://user-images.githubusercontent.com/21127166/42329425-f4911764-8070-11e8-8012-b1e57d154aa6.gif)

I discussed it with @janagombitova and she will take it forward.

The

**Comment by finnfiddle** [comment]
@nadiagorchakova @janagombitova I realize the value isnt changing when you change the y axis metric column because its just showing a count of the buckets. However, I wouldnt say the y-axis is redundant because it is still showing information to the reader. Im confused what youd like me to do. If I remove it then they wont be able to read the count unless they hover

**Comment by nadiagorchakova** [comment]
our initial idea was to automatically remove y axis label when count is selected. In the gif above, I removed it already manually. Jana had also other ideas how to improve the workflow.

**Comment by janagombitova** [comment]
@finnfiddle I spoke with two of our strong users to ask them about this issue and how they create bar charts. 

# User research 

"I never knew that only seeing the counts for the categories was possible. I always thought you need to select both x and y axis, so for cases where we just wanted to show number of submissions by submitter, for example, we used pie - what is not good if you have more than 2 categories. But it is good to know this is possible. In this case, it makes sense to start with the x axis for bar charts Because you get to see the initial count of the values in the variable before starting various aggregations and adding y-axis metric column."

"I usually start with the x axis, but in Lumen you need to select both y and x to see the chart being generated even if you only want to see counts for categories" 

# Problem

As mentioned above currently Jerome: 
1. selects the y axis 
2. selects the x axis 
3. sees the bar chart with the default aggregation set to 'mean' 
4. changes aggregation to 'count' 
5. sees that the buckets adjust and so does the y axis but the label remains as if the change is still dependent on the values from the data pointing to the y axis

The issue is that once Jerome selects count as the aggregation method, Lumen ignores the values set for the y axis and simply (and correctly) counts the categories on x axis. However, because the label remains shown on y axis, this is confusing and unclear. 

# Next steps 

Overall we need to take a critical look at the side panel editor - how the different options and elements are organised there to support the easiest and most clear workflow. I understand there are always exceptions, but lets see what we can improve overall.

I am creating an issue holding all these bar chart cases that I will link there so when looking at what the users does first and what next when creating a bar chart we can also look at the issues. 

Lets talk soon.

Here is the original mural board used for when creating Lumen visualisations: https://app.mural.co/t/akvo8194/m/akvo8194/1478624065782/e57b07e9bdf28011e96522735e27baf0beb4ee51

**Comment by janagombitova** [comment]
In our call about the visualisation editor we agreed that once we make that change we will then handle this issue as we made also the change to first select the x-bucket-axis and then the y-metric-axis. The idea is that then once Salim selects the buckets we can immediately show the bars based on count --> thus the defaulted aggregation type will be **count**. Once Salim selects the metric column for y-axis the aggregation type will automatically change to **mean** as it is now

**Comment by tangrammer** [comment]
so ... , talking with @finnfiddle about which is the proper place to implement this logic 
```
I’m wondering if this issue could be solved in client side :thinking_face:
of course it could be “hard-coded” in backend … but not sure if it’s the proper place …
```

**Comment by finnfiddle** [comment]
```yes I see what you mean but I guess I would argue that if it needs to be hard coded somewhere then it should be on the backend because thats the source of truth for client apps```
