### ISSUE TITLE
Wrap derived column code?

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1088]
# Context
A suggestion from Thomas. Derived column, javascript code, can we get it to wrap?

# Problem or idea
When an expression is long, it's easy to loose track of it when typing it into 'Javascript code' field.
It makes it more prone to errors and typos.

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
To add, Irene put the issue very simply: the input field is too small. Would it be possible to expand based on the needed space? Today she prepares her formula in another tool and then copies to Lumen simply because she cannot see the entire formula in Lumen.

**Comment by Kiarii** [comment]
In order to keep the entire JS code in view - in the JS editor field - the field should expand to accommodate the code as it written. This means that the side bar should be scrollable once its content are longer than its vertical bounds. By default, the field should at least be double its current size, but its bottom border should remain in view. 

A number of small tweaks will tag along as illustrated in the wireframe below:
- Rename the sidebar **New derived column** in line with what we did with category columns; it also gives a better flow of the fields beneath where they don't need to be overly named as New column title, New Column data type)
- Move the question icon next to the JS field label & change it to an info icon if possible
- Shorten the help text to **Reference columns as row[“Column Title”] or if the title is a valid javascript identifier: row.title**
- Change the derive column buttons font style from uppercase to **Capitalcase** (where only the first letter is capitalized) 
- Re-lable the DERIVE button to **Derive column**
- 'Unfloat' the Derive column and Cancel buttons so they are always at the bottom of the JS field

<img width="377" alt="Screenshot 2019-09-05 at 16 04 06" src="https://user-images.githubusercontent.com/12692444/64344273-d1300380-cff6-11e9-844e-18a9e1f3e440.png">
