### ISSUE TITLE
Delete a couple of instances

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1156]
# Context

I received a request from partner team to permanently close these two instances:
unc.akvolumen.org
mauritanie.akvolumen.org

For the first one the programme is over, and the second one dropped out of the the 9 country programme

# Problem or idea
comment from Jonas: I’ll discuss with Daniel how we want to do it. We could simply delete them, or perhaps archive them somehow

# Solution or next step
How could we solve it?

**Comment by kardan** [comment]
We should be able to set enabled to false in the tenants table. Will of course not remove anything from Keycloak or existing databases. @jonase let's chat about this

**Comment by kardan** [comment]
Remove a tenant should remove groups from Keycloak and also remove the corresponding database. We should then either set enabled to false or remove the row in the tenants table.

We should:
1. Verify that the enabled flag on the tenants table is enforced in the auth system
2. Verify the remove tenant script works as expected.
3. Remove tenants

**Comment by kardan** [comment]
Rambling thoughts
- We might not want to delete the tenant from the tenants table since then we potentially lose important business information related to billing. 
- What if we want to reuse a tenant label? 
- In Lumens auth path we rely on the information in the opened token. We never verify that a tenant still is valid. Since we also have an application cache for connections which we can't remove connections from at the moment there is a potential problem here.

**Comment by kardan** [comment]
Done
