### ISSUE TITLE
Dataset update logic very fragile

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1281]
# Context

Update of a dataset in Lumen will fail after any small change made to a Flow survey. Even changing the wording of a survey question will fail the update.
That is because derived column logic is built around typing the actual column name (survey question in Flow) for the transformation to happen. At least that's what I remember Jonas explained to me.

# Problem or idea
Even though it happens rare that Flow users change the entire survey structure (according to Jana), small corrections to survey questions happen more often. 
However, making a correction to a survey question in Flow would break dataset update in Lumen without users knowing what went wrong.

# Solution or next step
How can we make the update logic less fragile?
@kardan

**Comment by kardan** [comment]
Have been investigating this a bit and I think we can do the updates way better. But - it requires us to change how derived columns work. Today we reference the column title, (what's seen in the UI) we need to change that to have the actual transformation to reference the columnName (Flow question-id) for us. Otherwise, we'll break a lot of things. We have talk about this before and we should make it a priority to rework how derived columns operate.

**Comment by nadiagorchakova** [comment]
Jana enlightened Kiarii and me that there are actually two question IDs in Flow - internal numerical one and user-visible 'variable name'. You probably mean internal numerical one?
