### ISSUE TITLE
Flow import error 'null value in column Identifier' 

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1303]
# Context
When importing a Flow form, West Africa team gets the following error:

<img width="568" alt="screen shot 2018-02-26 at 11 06 01" src="https://user-images.githubusercontent.com/21127166/36674999-0dccf64a-1b08-11e8-9376-36255e143da3.png">

Both Gabe and myself checked raw data and couldn't find any issues with Identifier column or the specified row (and there are no null values in Identifier column)

# Problem or idea

The following Form form produces error at import:

https://mea-bf.akvoflow.org/admin/

Folder: 2. BOUBLE DU MOUHOUN-->Fiche de Collecte--> Fiche 6a: Inventaires des ouvrages ..
and the form Enregistrement AEP (Id 3450046)

I managed to reproduce the error in my own instance too.

# Solution or next step
@kardan Gabe and I had a look at raw data but we haven't noticed anything fishy...
Also, it's possible to load the same form as a csv file, so the problem seems to be with Flow import

**Comment by kardan** [comment]
Me and Iván debugged this for a bit. For some reason data-points at https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/import/flow_v3.clj#L58
does not always include a point with the id from the form-instance
 https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/import/flow_v3.clj#L61. Looking in the App Engine data-store we do have a point with the data-point-id. I have the feeling that somewhere from the data store to above lines in Lumen the data point disappears.

**Comment by kardan** [comment]
The issue is that we map over form-instances, using the dataPointId from the form instance to pull info about the data point from a list of data points. This list of data points has been crafted earlier based on the survey from the Flow API. The problem is that 2 form instances points to data points that _belongs_ to another survey. Hence the data point in question is not included in the list of data points. This results in Lumen trying to insert null data as the identifier. 

@muloem, @iperdomo and I concluded that to fix this properly we should fix the data on the Flow side.
