### ISSUE TITLE
Support for Flow geo-shapes in Lumen maps

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1355]
# Context

Flow datasets can contain geoshapes. For instance, shapes indicating the size and shape of a farmer's land.

# Problem or idea
Lumen currently cannot read those geoshapes coming from Flow.
During internal Lumen webinar on maps, a few people indicated it would be useful to visualise Flow geoshapes on the map.

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
## What is the status quo

Currently, Flow imported datasets that have geoshape data show as empty columns in Lumen. This data is stored as a json string holding the shape properties (as legth, area size, etc - metadata) and shape type and then the coordinates. 

Geoshapes are captured usually in agricultural projects to capture farm plots, but also in WASH to track water lines. Geoshapes coming from Flow can be either polygons, lines or points. In Flow, users can view the answers on the map where the shape is overlayed on the map layer. 

However, Flow maps only show data on the map with no possibilities for customisation and analysis. This is where Lumen maps step in. We often see data points colour coded by a specific variable layer over geoshapes to showcase relations between different variables. 

Today geoshapes collected in Flow cannot be used in Lumen. 

##  If this change is successful what might we observe?

First of all, in order to prepare for connecting Flow and Lumen we have decided to first tackle all the gaps where Flow and Lumen are not consistent and should. Making sure geoshapes can be used on Maps in Lumen is one of the missing bridges between Flow and Lumen. 

Having the functionality in Lumen will also enable us to fully remove the maps feature from Flow as Lumen will handle all the value it has today. 

Geoshapes are used mostly in agriculture projects and thus not widely used across our partners yet but growing. This change can help us support the growth towards agri projects and make not only demoing how to handle agri project data, but give us a stronger market position with this still unique functionality.

If we handle this data type in a simpler way we should see a decrease in the Flow geoshape data exports, as Salim will rather analyse the data in Lumen because of the benefit of simple visualisation creating and direct connection to Flow (new data streaming can be handled almost right away).

**Comment by tangrammer** [comment]
some results with greencoffee tenant 

<img width="1084" alt="Screen Shot 2019-05-17 at 16 59 26" src="https://user-images.githubusercontent.com/731829/57940091-07246d00-78cc-11e9-9452-a0fb86edaecd.png">

**Comment by tangrammer** [comment]
some links:
- http://postgis.refractions.net/documentation/javadoc/index.html?org/postgis/Polygon.html
- java bindings https://github.com/postgis/postgis-javaa
- http://strimas.com/spatial/r-postgis-2/ 
- https://www.postgresql.org/docs/9.5/datatype-geometric.html


- [ ] we need to update old datasets to retrieve geo data, currently we are not storing that . Important to note that we need to update a different `type` of column, so update could crash 🤔 

- [ ] Do we need "create-indexes" on new mapped types (Geoline, GeoPoint, MultiPoint )? https://github.com/akvo/akvo-lumen/blob/issue-2125-extract-geoshape-vals/backend/src/akvo/lumen/postgres.clj#L45

**Comment by tangrammer** [comment]
so https://dark-lumen.akvotest.org/ has the geoshape capability now :slightly_smiling_face:

you can import a new survey or update a old one to get the geoshape values
`updated` example: https://dark-lumen.akvotest.org/dataset/5ce52260-1c7a-4683-9f12-519b22b25c18
visualisation with `updated` dataset  example`
https://dark-lumen.akvotest.org/visualisation/5ce5834f-d9cb-4724-8e9b-4e813d6eb527

new `import`ed survey
https://dark-lumen.akvotest.org/dataset/5ce58371-ef9e-4da7-924d-0ffbfd926459

visualisation with new `import`ed dataset
https://dark-lumen.akvotest.org/visualisation/5ce58392-8421-403e-b132-a3959fee4647

**Comment by janagombitova** [comment]
Works like a charm. If we get extra feedback, will create a new issue
