### ISSUE TITLE
data uploader for shape files

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1364]
# Context

Lumen users (Akvonauts and partners) are reporting that it's very difficult and error prone to convert shape files to csv format that Lumen can load.
Some people use QGIS for that, others don't know how to deal with it at all. There is no easy and free online converter that our partners could use. The situation with shape file conversion defeats Lumen's aspiration to be intuitive and easy-to-use. 

# Problem or idea

Shall we consider building a shape-to-csv converter inside Lumen or as a service outside of Lumen?

@LarsSjogreen had the following arguments:

"Allowing for things (separate concerns) to be built without other parts of an application knowing about it is often a great thing. Having a way to build converters like this that just registers and "magically" shows up, gives a number of distinct positive effects. Work can be parallelized, changes can be done without risking that a change in one place will affect other parts of the code, deployment can be done without having to wait for a release window, the new functionality can be thoroughly tested (or put under automated testing if the contract/interface between the parts are well defined).

Of course, separating concerns come with a non-zero upfront cost, but the compound interest on monolithic "big ball of mud" code is in most cases much more deadly. In the end, the decisions on what is actually orthogonal and worth extracting out to a separate concern should be made by the developer team. A good team should strive for having a supple application architecture if the product is supposed to live and grow for longer than six months or so. Not investing in a decoupled design when the situation occurs will save some days or euros up front but will be the beginning of the downfall for a product."

# Solution or next step
How could we solve it?

**Comment by LarsSjogreen** [comment]
Solution idea(s):

Building imports conceptually as bash command pipelines (technically as microservices (FaaS?) that take file input and streams converted files out) that can be used from the UI (by, for example, checking checkboxes on import that will add and use the converters in the import step). The available converters (deduplication, UTF- conversion, shapefile->CSV, separation character normalization etc.) should be able to register (simply by adding it to a config file?) and show up (as a checkbox with a tooltip help) in the import dialog.

Conversion can, of course, also be done manually by the end user by up- and downloading the file to a separate web page. Less user friendly and more costly to keep extra UI's up to date.

Conversion can also be done by simply adding an URL as a prefix to the file URL in order to have the format conversion be done on the fly. (This has been tested and it works.) It's probably the least user friendly way of making the conversion, but it can be done as a first step and then have it handled by the UI at a later stage.
