### ISSUE TITLE
Implementation of a new vis library

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1365]
# Context

based on https://github.com/akvo/akvo-lumen/issues/1354

# Problem or idea
we need to reach feature parity + colour picker + other issues (to be discussed) that will enrich user experience

# Solution or next step

**Comment by finnfiddle** [comment]
## TODO

[ ] Pie
[ ] Print styles
[ ] Themes
[ ] conditional interactivity
[ ] Bar
[ ] Scatter
[ ] Donut
[ ] Line
[ ] Area

**Comment by finnfiddle** [comment]
# Proposed data formats

## Pie

```
{
  data: [
    { key: 'abc', value: 100 },
    { key: 'xyz', value: 200 },
    ...
  ]
}
```

**Comment by gabemart** [comment]
I'm going to leave my thoughts in multiple comments rather than one huge uber-comment to make them a bit more digestible, but the ordering of the comments has no significance.

---

Thought one:

I'm a big fan of the proposed approach of using the implicit ordering of elements in an array to separate out different axis values, without having to use labels like "x-axis" which are clunky and visualisation-specific.

But I'm not sure about the name `values` in the `metadata` object. There's an appealing purity to using the same key as we use in the `data` object, but it looks to me that the `values` array in the `metadata` object really functions as an ordered list of axis-specific metadata, using the order as the axis identifier (like we do with the values array for each datum). I think a name like `axes` would be clearer and better reflect the purpose of the array.

I also think that, almost inevitably, we will end up adding extra information to the `metadata` object over time, and if any of that extra information is not axis-specific, it might be confusing to have a `values` key on the same level as a `datasetVersion` or `serverTime` or whatever-we-end-up-needing key, because it's all just metadata.

I would propose:

````
  metadata: {
    axes: [
      { label: 'Temperature' },
    ]
  },
````

**Comment by finnfiddle** [comment]
just copying and pasting from slack for reference:
```
its like for a bar or pie you have one series containing single values;
for a scatter you have one series containing multiple values;
for a stack you have multiple series containing single values;
and for a multiline chart you have multiple series containing multiple values
```
so that I can propose a different format in this context.

@gabemart regarding `metadata.axes` I get what youre saying and I dont have much preference about this but I think we could think of a better word than `axes` - let's discuss.

**Comment by finnfiddle** [comment]
# Proposed Formats V2

## Pie

```javascript
{
  series: [
    {
      key: 'hum',
      label: 'Humidity',
      values: [100, 200, ...],
    },
  ]
  metadata: {
    values: [
      { label: 'USA' },
      { label: 'UK' },
      ...
    ]
  },
}
```

## Bar

### Simple

```javascript
{
  series: [
    {
      key: 'hum',
      label: 'Humidity',
      values: [100, 200, ...],
    },
  ]
  metadata: {
    values: [
      { label: 'USA' },
      { label: 'UK' },
      ...
    ]
  },
}
```

### Grouped/Stacked

```javascript
{
  series: [
    {
      key: 'hum',
      label: 'Humidity',
      values: [100, 200, ...],
    },
    {
      key: 'temp',
      label: 'Temperature',
      values: [100, 200, ...],
    },
    ...
  ]
  metadata: {
    values: [
      { label: 'USA' },
      { label: 'UK' },
      ...
    ]
  },
}
```

## Scatter

Humidity is used for x-axis position, temp for y axis position:

```javascript
{
  series: [
    {
      key: 'hum',
      label: 'Humidity',
      values: [100, 200, ...],
    },
    {
      key: 'temp',
      label: 'Temperature',
      values: [100, 200, ...],
    },
    ...
  ]
  metadata: {
    values: [
      { label: 'USA' },
      { label: 'UK' },
      ...
    ]
  },
}
```

## Area/Line

Humidity is used for x-axis position, temp for y axis position:

```javascript
{
  series: [
    {
      key: 'hum',
      label: 'Humidity',
      values: [100, 200],
    },
    {
      key: 'temp',
      label: 'Temperature',
      values: [100, 200],
    },
    ...
  ]
  metadata: {
    values: [
      { label: 'USA' },
      { label: 'UK' },
      ...
    ]
  },
}
```

**Comment by finnfiddle** [comment]
comments from @gabemart were:

* metadata feels strange because sometimes there are values that need to be stored in the metadata that are common to all series (eg dates in a line chart) - therefore we thought it's more logical to rename `metadata` key to `common`.

**Comment by finnfiddle** [comment]
# Proposed Formats V3

Changes:

* renamed `metadata` to `common`
* wrapped values in objects so that the common config can be merged into each series more easily
* and renamed `values` to `data` because of the previous point - it felt weird to have `series[0].values.value`

## Pie

```javascript
{
  series: [
    {
      key: 'hum',
      label: 'Humidity',
      data: [
        { value: 100 },
        { value: 200 },
        ...
      ],
    },
  ]
  common: {
    data: [
      { label: 'USA' },
      { label: 'UK' },
      ...
    ]
  },
}
```

## Bar

### Simple

```javascript
{
  series: [
    {
      key: 'hum',
      label: 'Humidity',
      data: [
        { value: 100 },
        { value: 200 },
        ...
      ],
    },
  ]
  common: {
    data: [
      { label: 'USA' },
      { label: 'UK' },
      ...
    ]
  },
}
```

### Grouped/Stacked

One parent bar per country, each parent bar contains children for different types of precipitation etc...

```javascript
{
  series: [
    {
      key: 'rain',
      label: 'Rain',
      data: [
        { value: 100 },
        { value: 200 },
        ...
      ],
    },
    {
      key: 'snow',
      label: 'Snow',
      data: [
        { value: 300 },
        { value: 400 },
        ...
      ],
    },
    {
      key: 'hail',
      label: 'Hail',
      data: [
        { value: 100 },
        { value: 200 },
        ...
      ],
    },
    ...
  ]
  common: {
    data: [
      { label: 'USA' },
      { label: 'UK' },
      ...
    ]
  },
}
```

## Scatter

Humidity is used for x-axis position, temp for y axis position:

```javascript
{
  series: [
    {
      key: 'hum',
      label: 'Humidity',
      data: [
        { value: 100 },
        { value: 200 },
        ...
      ],
    },
    {
      key: 'temp',
      label: 'Temperature',
      data: [
        { value: 100 },
        { value: 200 },
        ...
      ],
    },
    ...
  ]
  common: {
    data: [
      { label: 'USA' },
      { label: 'UK' },
      ...
    ]
  },
}
```

## Area/Line

Humidity is used for x-axis position, temp for y axis position:

```javascript
{
  series: [
    {
      key: 'hum',
      label: 'Humidity',
      data: [
        { value: 100 },
        { value: 200 },
        ...
      ],
    },
    ...
  ],
  common: {
    data: [
      { label: 'Jan', timestamp: new Date('Jan') },
      { label: 'Feb', timestamp: new Date('Feb') },
    ],
  },
}
```

**Comment by gabemart** [comment]
I think this is good progress. Couple of remaining small questions:

* Where do the 'key' values come from? Presumably they are not user-entered, so how does the backend generate them?

* For the Area/Line example, where do we think the `label` value comes from? I guess the label is really just a custom date display format (e.g. `Jan` or `Sunday` or `2017`). Perhaps this label value is generated in response to some user configurable option in the visualisation spec? Or maybe the backend chooses a display format automatically based on the total date range from the highest to lowest value in the array (e.g if the total range is 200 years use `$year` and if the range is 12 hours use `$hh:$mm`)? I'm almost wondering if the process of converting a timestamp to a user-readable date in a custom format might be better on the client to make it easier to take things like timezones into account. What do you think?

**Comment by finnfiddle** [comment]
@gabemart 

* Im trying to think if we even need keys for series. On the frontend we need keys for each individual datapoint so that react motion can animate properly - however these could be generated from the respective series and value indexes I guess. React will also need keys for series if they will be entering and exiting the chart. https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318 - Im not quite sure if we'll run into problems without keys to be honest. I guess we can try first without keys and if need be add them. I'm sure we can find a way to create unique keys for series based on the column and aggregation method maybe. what do you think?
* I agree and think labels should be generated on the frontend where possible (ie for dates)
