### ISSUE TITLE
Photos on map autorotated to landscape mode

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1398]
# Context

If a Flow survey contains photos, one can add them to a map pop-up.

# Problem or idea

Harro reported an issue while using a dashboard for Ground Truth 2.0 project. A photo was taken in portrait mode and is displayed so when you follow the photo link from raw data.
However, on a map in Lumen, photos taken in portrait mode by default are rotated to landscape mode. 

Example:

<img width="1277" alt="screen shot 2018-05-02 at 09 57 25" src="https://user-images.githubusercontent.com/21127166/39511907-573a60aa-4def-11e8-8d35-e692676b684c.png">
That was when using Chrome.
Interestingly, when I open the same pop-up when using Firefox, the image is auto-rotated correctly:

<img width="1273" alt="screen shot 2018-05-02 at 10 04 39" src="https://user-images.githubusercontent.com/21127166/39512186-48900f7c-4df0-11e8-9bc5-4a2f6108f470.png">

Link to dashboard: https://gt20-belgium.akvolumen.org/s/7Zig7JBobOg

# Solution or next step
I remember we've spotted this problem earlier but I don't think we have investigated it yet.
Any thoughts @Finn @gabemart ?

**Comment by gabemart** [comment]
@nadia Firefox is the only browser that supports the css that enables this functionality, which explains why it works in FF but not chrome 

https://caniuse.com/#feat=css-image-orientation

This issue arises when an image is saved in one orientation (the "incorrect" orientation as seen in Chrome) but has EXIF data that tells user agents to rotate the image before displaying it.

The problem is that browsers ignore EXIF data when an image is used as the `src` of an `<img />` (except FF when the "from-image" css is set)

I also don't think we can access the EXIF data from client-side javascript because of CORS issues

The only solution that comes to mind would be to build a proxy API into the backend which rotates the images into the "correct" orientation based on EXIF, but this would not be trivial or quick

Although this issue affects lumen it's also an issue for many other web applications. There's an issue discussion at https://bugs.chromium.org/p/chromium/issues/detail?id=158753 which indicates the Chromium team is considering adding support but has not done so yet

**Comment by gabemart** [comment]
Another approach would be to display the image inside an iframe - browsers generally use the relevant EXIF data when displaying an image as a document rather than part of a page. But this won't work because many hosting services now set headers to prevent iframe usage, and further there's no way to style iframe contents to get the image to display at an acceptable size.

**Comment by nadiagorchakova** [comment]
I see, thanks for looking into it Gabe. I'll advise people to take photos in 'correct orientation' then. Or to use firefox to view the map containing such photos. 
If other browsers like Chrome seem to be aware of the problem and will potentially resolve it at some point, there is no sense, I think, in investing so much time in this non-trivial issue.
