### ISSUE TITLE
Cannot go back to white colour in raster theme

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1426]
# Context
By default the start colour for raster theme is white. 
When I pick other than white colour, but decide eventually to go back to white, it's not present in the colour palette. 

![ezgif com-gif-maker 3](https://user-images.githubusercontent.com/21127166/40051156-0c370aea-583a-11e8-954d-a76618747365.gif)

# Solution or next step
If white colour was a defaul colour I should be able to pick it again.

**Comment by janagombitova** [comment]
<img width="447" alt="screen shot 2018-07-12 at 10 45 15" src="https://user-images.githubusercontent.com/12456965/42622461-b6e56762-85c0-11e8-88e7-59c77a7c2e44.png">

So you can now select white as a colour, but it is hidden in a sense at the end of the colour picker and seems it is not there. You only see it if you hover over. 

@finnfiddle any ideas on how to make it more "visible"?

**Comment by finnfiddle** [comment]
@janagombitova I couldnt find a way to style the color blocks individually because they are generated by a 3rd party lib and its API doesnt support configuring their styles. So I replaced the colorpicker with the new one that I used for the new visualizations. However, the original task was about being able to go back to default colors if the user desires and this would not be possible with the new color picker because it doesnt have the same color palette as the old one. So what I did is add the old palette to the new one at the top. Its a bit ugly but achieves the desired result. A better approach imo would be to just change to the new palette but I guess this is not an option or is it?
<img width="1440" alt="screen shot 2018-07-12 at 12 49 21 pm" src="https://user-images.githubusercontent.com/4628721/42627579-1db255da-85d6-11e8-8a27-bac84ec5d43f.png">
<img width="1440" alt="screen shot 2018-07-12 at 12 49 11 pm" src="https://user-images.githubusercontent.com/4628721/42627580-1de8833a-85d6-11e8-908b-5467893aa6db.png">

**Comment by finnfiddle** [comment]
@janagombitova so question is should I merge the PR as is or should I remove the old colors? or something else?

**Comment by janagombitova** [comment]
@finnfiddle I absolutely agree that it would be better to have the new colour picker (much nicer and more options) across all occasions when you can choose a colour. Would this change affect existing maps in one way or the other? Colour change?

**Comment by janagombitova** [comment]
After discussing with @finnfiddle we decided to update the colour picker to the new one he integrated. The consequence for existing maps is that their colours will remain but at point of edit Jerome will have to use the new options.

**Comment by janagombitova** [comment]
Looks good. 👍 Here is a follow up issue we need to discuss if we want to address or not (but not in this iteration): https://github.com/akvo/akvo-lumen/issues/1566
