### ISSUE TITLE
Bar chart differences

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#1470]
There is a lot of differences in both Y (scale) and X-axis numbers on the following bar chart. We should investigate what's going on.

https://demo.akvolumen.org/visualisation/58c8a563-a036-4c2f-a16c-b8ffb7b42382
https://dark-demo.akvolumen.org/visualisation/58c8a563-a036-4c2f-a16c-b8ffb7b42382

**Comment by gabemart** [comment]
I need to dig in, buy my suspicion is that under the old system, selecting "number of buckets to show" as 25 will *automatically* add a "sort" of some kind, even though there isn't one explicitly specified by the user, and under the new system, it doesn't. That would explain why different buckets are shown in the old vs the new chart

**Comment by gabemart** [comment]
I've confirmed that's what happening.

Under the old system, when you set "Number of buckets" to some value below the actual number of buckets, and you don't select a sort, the system will begin from the first row in the dataset (i.e using the dataset row order) and "look" for buckets until it reaches the number you have shown

![image](https://user-images.githubusercontent.com/2589977/41526511-639c9298-72dc-11e8-9209-112ffc510e46.png)
![image](https://user-images.githubusercontent.com/2589977/41526536-72ecde38-72dc-11e8-8970-76c528e9b7aa.png)

Under the new system in the same scenario, the system will aggregate for every bucket in the dataset, and then sort the buckets by the bucket value (i.e the actual key used to define the bucket), then show the first 25 after the sort

![image](https://user-images.githubusercontent.com/2589977/41526602-9d3a3e56-72dc-11e8-8aff-71d438e8a605.png)

To be honest, I think the new system makes more sense than the old system, but I guess it's a problem to change charts in product. Should we try to replicate the old behaviour, even though it's a bit weird?

**Comment by kardan** [comment]
I'm tempted to say that we should build a product that makes sense. If the old behavior was a bit off (probably because we didn't think of this case) then maybe a change is not the end of the world. @nadiagorchakova & @janagombitova what ya think?

**Comment by gabemart** [comment]
Perhaps a relevant question is "how often is dataset row order more significant than the buckets themselves?"

also, here is another comparison that I think makes the difference more clear

## Old
![image](https://user-images.githubusercontent.com/2589977/41527322-ac8cc3a4-72de-11e8-9304-40c74169c168.png)

## New
![image](https://user-images.githubusercontent.com/2589977/41527329-b3b923f2-72de-11e8-85c1-027481eccc7c.png)

**Comment by gabemart** [comment]
Had a call with @janagombitova and @nadiagorchakova on this issue

The source of the existing behaviour is the datalib library that underpins vega. An implementation artefact of that library is that most buckets are not sorted, but whole-value integer values are sorted by bucket key.

We agreed that the existing behaviour doesn't make sense in lumen, and is potentially misleading for users, and for that reason we should keep the new behaviour, even though it will change some charts in production. It will be annoying for users to change charts in production, but that is less wrong than continuing to produce charts that are potentially misleading because of the arbitrary sorting behaviour we currently have. We need to communicate clearly to users in the release notes about this change and the reasons behind it.
