### ISSUE TITLE
Bar chart show hundreds of the decimal point

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1551]
# Context
 
I managed to create the following graph:

<img width="1280" alt="screen shot 2018-07-12 at 12 17 24" src="https://user-images.githubusercontent.com/21127166/42627637-ddbe2f92-85cd-11e8-847c-f3223bbe5b1b.png">

https://global.akvolumen.org/s/H1spaUKjORk

# Problem or idea
The y axis shows 0.0 for every interval. If for a monitoring month, or any other column, the mean number is 0.0, than probably there should be no bar visible for this monitoring month at all.

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
The reason why we show 0.0 in each line is because the actual mean value of the bar is 0.03. We could show the values on y axis to the hundreds of the decimal point, if relevant. 
<img width="843" alt="screen shot 2019-01-07 at 12 44 04" src="https://user-images.githubusercontent.com/12456965/50766613-2f46f400-127a-11e9-8f28-4b4e26a88f2b.png">
