### ISSUE TITLE
Date should be the same across the dashboard editor

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1554]
# Context

After discussing the issue with @janagombitova we agreed that the editor should show the 'data last updated' for vis shown on the left as well. Currently they show the date when last edit was made on the vis itself, e.g. changing colour of geopoints.

<img width="893" alt="screen shot 2018-07-13 at 10 21 40" src="https://user-images.githubusercontent.com/21127166/42682049-ba0f6018-8689-11e8-90e4-28d7b5d9e9d2.png">

# Problem or idea

Showing different dates confuses the user. It might appear as a bug to an outsider. Plus, I think, it's more valuable to see here when the dataset was last refreshed.

# Solution or next step
How could we solve it?

**Comment by finnfiddle** [comment]
So I resolved this and @janagombitova also had a comment: "And ideally, it should show on the left (in the picker) in the same format: Data Last …" - so I took the liberty again of restyling the visualisation list a little so that it matches the style of the library. I did this because we are showing the same information in the same format and in my mind it makes sense to have some consistency in the ui too. Let me know if you dont like it.
<img width="1440" alt="screen shot 2018-07-13 at 2 48 49 pm" src="https://user-images.githubusercontent.com/4628721/42690260-3834b7f0-86ac-11e8-8d8c-13dea779cd73.png">
<img width="1440" alt="screen shot 2018-07-13 at 2 48 44 pm" src="https://user-images.githubusercontent.com/4628721/42690261-38609014-86ac-11e8-95df-88e3e633e354.png">
