### ISSUE TITLE
Support full JS in derived columns 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1585]
# Context
*Why do we add this issue?*

With changes to this issue: https://github.com/akvo/akvo-lumen/issues/1296 we can now support full JS in transformations. This change was introduced to enhance Lumen's security. The implementation has no change to the users, Jerome continues to put in expressions as before, we automatically add `return` to it to execute. In the UI the validation allows for expressions and not full JS code. 

# Problem or idea
*What is the cause?*

The current implementation that Jerome sees does not give him the option to fully utilise the possibilities of JS. We can create a way for Jerome to decide if we wants to use an expression in his transformation or write the full code. 

# Solution or next step
*How could we solve it?*

Ideally we want to simplify how transformations are handled in Lumen, moving away from writing expressions or code, to having a interface that can guide anyone in the transformations you want to do. Supporting more advance JS transformations is heading in the opposite direction of this goal. On the other hand, if there is a current gap that Lumen users cannot do, we can fill it. 

The next step is: 
- to research with current Lumen users, what expressions do they use most in Derived columns 
- to research with current Lumen users, what is it that they want to do, but cannot currently and why do they want to do it (what value)
- evaluate if this change would be beneficial to implement or not

**Comment by nadiagorchakova** [comment]
Hi there, I did a quick survey to poll a few Akvonuats about the use of derived column and what is it that they cannot do right now.

Who took part in the survey: Joy, Geert, Veerle, Molo, Guneet.

You can find full responses to the survey here: https://docs.google.com/forms/d/1fkcXmG5nI-8c7UiuligyuFoSz_zWiHdOHd0eT4v9Vyc/edit#responses

The overview:

**What expressions do you use most in derived columns?**

- mostly if statements , array splits and concatenations
- Scoring, merging, splitting, date manipulations, (date) calculations. 
- creating groups, e.g. row ["column name"] < "number" ? “text" : (row["column name"] < number ? “text" : etc.
- parseFloat(), split(), indexOf()
- nested switch statements, split, addition

**What is it that you want to do but cannot currently?**

- Because lumen currently allows access only to row data and not column data, it limits the use of the derived columns. Ex: I want to mark all points in red where the time taken to conduct the survey is 20% above the average survey  time. Lumen does not allow computation of a column dynamically. Hence all visualisations where you are trying to compute dataset wide values dynamically cannot be executed
- a slightly complex mathematical calculation (like roots, logs), including logical statements

I also asked what, in their opinion, is the most critical feature that the derived column lacks at the moment and not a single comment had to do with calculating values.  Most of the comments were about the usability and standardization.

If you'd like to have a partner's point of view as well, I've noticed that users of Sierra Leone instance (Jesse?) are using the derived column functionality. Would be interesting to hear their opinion.

**Comment by tangrammer** [comment]
@nadiagorchakova that survey is really useful!

**Comment by tangrammer** [comment]
Regarding `a slightly complex mathematical calculation (like roots, logs), including logical statements` 
I've tried https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sqrt and worked fine ... example `Math.sqrt(row['Instance id'])`

**Comment by tangrammer** [comment]
for more details in splitting cascade response values, here a dataset https://demo.akvolumen.org/dataset/59e5c53c-09a4-4b80-bc83-5ef76a338184 
column=> `L'agent se trouve ou?` and example value=> `BAMAKO| DISTRICT DE BAMAKO| COMMUNE V| BADALABOUGOU` ... as far as I know we could set up a new transformation operation for it, that internally could reuse derive functionality

**Comment by janagombitova** [comment]
# Backgroud
Over the past weeks, we have been working on making the most used Derived column cases more user-friendly. We looked when these cases are and how to address them. Based on the user research and design validation we learned that there are two groups of tasks done using the derived column javascript transformation: 
1) Deriving a column based on one column
2) Deriving a column based on more than one column

You can find the notes scattered here: https://github.com/akvo/akvo-lumen/issues/671 and here: https://github.com/akvo/akvo-lumen/issues/2071

## 1) Deriving a column based on one column
In this case, we have pushed out a few new transformations to handle the most common cases: 
- Extract multiple values to handling Caddisfly and geoshape data 
- Split columns to handle Flow cascades or other combined cells 
- Category column to create ranges, value groups, assign points for scoring

## 2) Deriving a column based on more than one column
When looking at how to handle these cases we realised it is not easy to create one UI and UX that would fit all examples. Some formulas use simple mathematic operations like sums, where others are more based on if and or statements. They all have in common that they are based on more than one column. 

See examples here: https://drive.google.com/drive/u/0/folders/1uZtpArQV0vMCRID3SpEoLGpnVUWdewnj

# Opportunity 
We want to create a more user-friendly approach to tasks where Salim derives a column based on multiple columns. We also want to keep the flexibility of the current Derive column javascript transformation for more advanced users.
