### ISSUE TITLE
Change visualisation type

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1673]
# Context
*Why do we add this issue?*

When creating visualisations you first select the visualisation type, then dataset and then the columns and other settings. Salim often wants to explore the data and ‘playing around' with them to see what is the best way to visualise that particular value or find patterns. He does not always have it clear what visualisation he will create, he sometimes just goes in and tried.  

# Problem or idea
*What is the cause?*

When you change visualisation type, you have to start from scratch. As in you have to reselect the data set, reapply the folders etc. This makes it difficult to explore the data by trying out different visualisation etc as you always have to create a new one. 

# Solution or next step
*How could we solve it?*
How might we make it possible that when you create a visualisation and then change the type, the visualisation renders new with some of the items still selected like dataset and the bucket column (or other)?

**Comment by finnfiddle** [comment]
Looking at it I see that when you change the vis type it keeps the dataset selection but it erases the mappings to the visual variables (eg. x axis, bucket, etc). So I will attempt to remap these when the type changes. @janagombitova agree?

**Comment by janagombitova** [comment]
@finnfiddle sounds good 👍

**Comment by finnfiddle** [comment]
@janagombitova Ive implemented it so that if you change from type A to type B it will attempt to reassign the column mappings. However, if you then change to type C it will attempt to remap from B to C and will not take into account the original mappings from type A. I did this for technical reasons to try keep the data purer for the visualizations and not have unused column mappings stored in the data. Not sure if that makes sense?

**Comment by janagombitova** [comment]
Makes perfect sense to me.
