### ISSUE TITLE
Make sure UI respects Flow permissions.

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#1951]
# Context
We're changing how permissions work, see https://github.com/akvo/akvo-lumen/issues/1950

# Problem or idea
We have to make sure things like dataset dropdown selectors uses a filtered list of datasets. This might fall out automagically if we make sure to load the correct datasets into the redux store.

# Solution or next step
Review the UI.

**Comment by tangrammer** [comment]
IMO `client` side doesn't need further changes thus `backend` delivers so far just auth data 
anyway @finnfiddle, could you double check? :)

**Comment by finnfiddle** [comment]
Im not very familiar about what will physically be different on the frontend @tangrammer. Could you give me some guidance about what I should be looking for?

**Comment by janagombitova** [comment]
From the few tests that I have run it seems that in the dropdowns the users only sees what she should see. So all is working well on that end. 

However, because initial Library loading now can take a bit more seconds, we could use a visual cue indicating loading is happening. Right now once Salim logs in, he sees the Library UI but it is 'empty' and he can assume something is broken, even though we are just loading in all the elements. A loading spinner or anything visual you would recommend @finnfiddle to show in the Library while elements are loading can help us avoid confusion.

**Comment by janagombitova** [comment]
We are in production!

**Comment by tangrammer** [comment]
@finnfiddle Loader image doesn't disappear when "api/library" data is received and collections are empty ... 

<img width="1078" alt="Screen Shot 2019-05-02 at 09 40 40" src="https://user-images.githubusercontent.com/731829/57061929-fe724b00-6cbe-11e9-8b92-b2fa6433663c.png">
