### ISSUE TITLE
Show which columns are sorted

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-lumen#198]
In the mockups we show in the column header which columns are sorted and a button to remove the sort.

**Comment by jonase** [comment]
This one needs some styling before possible PR

**Comment by gabemart** [comment]
Unfortunately, the styling for this runs into the same issue that we ran into for context menus. The data-grid component aggressively suppresses any overflow from its container, so trying to show a label positioned relative to a data grid element (the column header in this case) but outside the data grid container is a substantial task, especially when horizontal scrolling is concerned - more substantial than perhaps is warranted for this feature. I think we should hold off on this if there's a possibility we might swap out the data-grid component, as discussed. If not, I'll need some time to think how best to approach this, because I suspect this issue is going to keep cropping up as we add functionality

**Comment by jonase** [comment]
Yes, I suspected this would be tricky.

Den fre 3 jun 2016 17:09Gabriel Martin <notifications@github.com> skrev:

**Comment by jonase** [comment]
Does it have to be outside the header cell?

Den fre 3 jun 2016 17:16Jonas Enlund <jonas.enlund@gmail.com> skrev:

**Comment by gabemart** [comment]
Not necessarily - I'm testing out some other approaches now

**Comment by gabemart** [comment]
![image](https://cloud.githubusercontent.com/assets/2589977/15784759/cf872d46-29ab-11e6-9392-c73d3030f8a7.png)

This is about the most I can fit in to the available space (I also increased the column header height by 10px). Pushed now
