### ISSUE TITLE
Password protect shows error but works 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2024]
# Issue 

When setting up a dashboard to be password protected Lumen shows the error that it failed (in the UI) even though it worked. 

![screen shot 2019-03-06 at 08 37 26](https://user-images.githubusercontent.com/12456965/53863706-227d1d00-3feb-11e9-916c-6f3b27836636.png)

## Steps to take to recreate
1. Created a dashboard and shared it
2. Turn on password protection and immediately get the error
3. Added the password and hit save
4. Refresh shared dashboard and the password protection is enabled

# Created via Reamaze:

Link: /admin/conversations/akvolumen-support-request-number-192596-from-camille-at-akvo-dot-org

**Comment by kardan** [comment]
The problem is that once the user hit the "protected switch" the client issue a PUT request to the backend. This request has a payload with {"protected" true} but no password. Hence the backend responds with a 400 error. If the user continues to add a password and hit the save button all is fine. 

We should probably not send a request from the client until the user hits the save button.

Not sure what's going on with the funky circle floating around the error message.
