### ISSUE TITLE
Better handle Flow multiple-answer data 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2225]
# Context

## Why do we add this issue?
We aim to make working across Flow and Lumen as smooth as possible what means Lumen should be able to handle all special Flow datatypes and make it easy to analyse them for our users. Our goal is not to make Lumen the better Excel, but to make it the simpler Excel ;) We aim to make it easy to go from a table, where Salim has no clue what he is looking at to having an idea about what the data is telling him. 

# Problem or idea
## What are multiple-answer questions? 
In a Flow survey or any other for that matter, option questions are one of the most preferred question types. They require you to define a set of options the respondent chooses from and have the benefit of keeping the dataset clean. You can have two types of option questions:
* where you can choose only **one** option
* where you can choose **multiple** options. 

This issue focuses on the case of multiple options. 

## What is the current status quo? 
Currently, in Lumen, multiple option questions are imported into a single column with the options divided by a pipe: Example `orange|red|yellow`. As with Repeated question groups (https://github.com/akvo/akvo-lumen/issues/2127) we have the same situation where there are more answers than rows (one row has more answers for one column). 

When visualising this column, you cannot do that much. Almost each row can hold a different combination of options thus they seem unique resulting in too many categories to visualise. What Salim can do is split this column to more columns. Then each option is added to a separate column. The problem here is that we do not create columns based on the option text, but based on the order. So I can have the options: red in the 1st, 3rd and any extracted column. 

To conclude, it is today impossible to analyse this data in Lumen when directly importing the data from Flow. 

## Lessons learned from Flow and current Lumen users 

In Flow we handle these columns in two different ways: 
* Data cleaning export handles the data the same way Lumen does 
* Data analysis export creates also a column for each option and then indicates if that option was selected

![32102826-456a588a-bb1e-11e7-9d70-36fb70b78b23](https://user-images.githubusercontent.com/12456965/60353325-18cc5a80-99ca-11e9-8243-918216cc9613.jpg)

## Analysis needs 
When talking to some Lumen users today they do not know how to handle having all options in one cell and the current Split transformation does not work for them. When looking at the option to create a separate column per option they were not that enthusiastic either as it will mean creating separate visualisations per column. **What our users are trying to do is to understand all the answers to that one question - in one visualisation - and the option frequency and perhaps correlation with another column**.

Bar charts are used most in this case.  

![Screenshot 2019-09-06 at 14 38 11](https://user-images.githubusercontent.com/12456965/64426771-c5ecde80-d0af-11e9-8051-96f5c363060e.png)
*This is an example from Irene, where each bar is a defined option. This way she can see the frequency for each option.*

To create them: She currently creates a separate sheet from their Flow data where they have one column for the multiple answers and put every single option in a row. So one submission would be on more rows with some properties copied over to the row to be able to link back to the original dataset. Irene (a colleague in Kenya) has an R formula she uses to create such subsets of datasets to analyse this type of data.  

See example data here: https://docs.google.com/spreadsheets/d/15RvZpqDV0nh_65JNxcBSA71mCluARl_oujn4OPhlWWU/edit#gid=0

## If the change is successful what might we observe? 
* more use of Lumen and faster user adoption, as we will handle a hard problem they have today 

# Solution or next step
## How could we solve it?
- as we also need to see how to handle Repeated question groups it might be worth thinking is we can handle these both issues in a similar way considering in principle they are quite similar
- as multiple-answer data (multiple option questions) are not just a Flow speciality we should see if we can create a way to handle this issue for also datasets that come from a file or link.
- would there be a way to visualise this column without having to change how they show in the dataset and if Salim wants to see them in the dataset use Extract multiple values to create a column per option?

**Comment by Kiarii** [comment]
After talking to Geert, Molo and Irene, I think that we have a good basis on which to proceed; I would want us to go on this together, so starting out with a recap of the user needs and the storymapping how to address them.. There are a number of subtle details that would require our being in sync on this one. In a nutshell, on the analysis side, there are two umbrella needs: 
1. Choice aggregation mainly: Count,  ..
2. Side-by-side visualization of choices (Count) in the same chart e.g. via stacked or split barchart
3.

**Comment by janagombitova** [comment]
As an extra note: With #2131 we will allow users to visualise more than one number column in bar chats. This might be a way to analyse multiple option question data is each option is split to its own column (following the pattern on how Flow Data analysis export treats this data). 

In the Discovery, let's check if this works. If so, it might be an alternative worth considering on how to transform this data in the grid and then visualise it. It may not be the most elegant solution but we can then compare the usability and implementation effort to other ideas we have.

**Comment by muloem** [comment]
Talked with @Kiarii today on how to proceed with this. 
- We will look into what kinds of analysis users want to be done against the responses in a multiple option column (also compare this with the cascade question splitting and analysis that we currently have)
- We will keep the presentation of multiple answers in the current grid style if we go ahead to split the column.

**Comment by Kiarii** [comment]
In response to some of the concerns expressed earlier on;
> some Lumen users today they do not know how to handle having all options in one cell and the current Split transformation does not work for them.

This could be attributed to the current presentation of MOQ data in Lumen where unselected options are simply omitted from the final data. This makes the analysis within lumen challenging. It requires manual transformation and analysis in excel as pointed by Jana
<img width="285" alt="Screenshot 2020-02-04 at 9 38 05" src="https://user-images.githubusercontent.com/12692444/73723631-2a30ce80-4732-11ea-9557-32d87ca7f71a.png">
 
To address this specific concern, ideally, the data should include un-selected values so that upon splitting the parent col or doing analysis, all option values are held in their positions in the resulting 'matrix'. Additionally, the visualization of MOQ split data should 'pick' by default all child cols upon the selection of any one of them - given that the main analysis requirement is a comparison of all the options. We could provide a means for the user to remove/hide some options if for some analysis they are only looking at specific options.. 

> When looking at the option to create a separate column per option they were not that enthusiastic either as it will mean creating separate visualisations per column. What our users are trying to do is to understand all the answers to that one question - in one visualisation - and the option frequency and perhaps correlation with another column.

From the research we had done with the partner team, one of the requests made regarding MOQ data was to lessen the effort and time to analysis. If that would mean providing some out-of-the-box chart for visualizing MOQ data, without requiring the user to make split transformations (we have to decide whether we do this by default or else support the analysis the analysis of MOQ data while it exists in parent col)

Other considerations to keep in mind:

- We have to decide whether to present MOQ data in binary format; 1s for selection, 0:unselected, or Yes and No respectively..
- Provide basic data summary - e.g. Flow charts
- Reduce time & cognitive effort required to digest the data and determine a course of action
- Enable conversion of out-of-the-box data summary charts into visualizations
- Provide a quick snapshot of “other” responses if this is used
- If we auto-split choices into cols, Lumen has to keep (in mind) the relationship of child cols with parent question, so that analysis knows that all resulting children cols are part of the same
- [Preliminary wireframes for MOQ data](https://invis.io/KPUJ89PM578#/372819231_0-3_GRID_-_MOQ) presentation on the Grid..

**Comment by janagombitova** [comment]
Closing this issue as the main use case is handled in #2620 and the rest we will learn and implement as we go
