### ISSUE TITLE
Flow questions can have same value but different group

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2437]
# Context
Flow allow the final user to define questions with the same "name" but different groups. So the question identity  depends on the context of the group

# Problem or idea
Lumen doesn't expect to have duplicated column names. One direct consequence is js-transformation, that uses that name to derive new values

# Solution or next step
🤔

**Comment by tangrammer** [comment]
After talking with @Kiarii about how better handle this question duplicated problem, we agree on adding the difference as a suffix in the question title
something like that... "example-question-duplicated-X", "example-question-duplicated-Y"
Now we need to decide the suffix value:
should we use just a numeric index? or should we add the flow group name there?
I've just checked that lumen receives the flow group in the import/update processes so we are able to use it

**Comment by janagombitova** [comment]
My initial hunch was to go with the simple numeric index. But if we have the question group info coming from Flow, it might be more informative to use the group index (G1, or G3) if we have that data.

**Comment by Kiarii** [comment]
I had the feeling that using the group name or number (as a prefix or suffix) for repeating questions only will make it look weird; it was, it was the reason we had settled for numbering for now; so that if there is a question "example-question-duplicated-X" the user can expect a Y or more of the same.. once we visit RQGs this might need to change..

**Comment by janagombitova** [comment]
With Juan we spoke yesterday and agreed to handle this issue to: 
* [ ] add Flow's question groups to the data table as step 1. Not only will this bring the Flow user view of data closer in Lumen, but it also solves the issue of duplicated column headers without expanding the column headers. (the next step would be to see how we can make use of the question groups in question dropdowns across Lumen)
* [ ] when creating a derive column with javascript, warn the user that she selected a column which is duplicated and tell her to refer to the question group too 
* [ ] when updating a Flow dataset with an existing transformation, fail the update because oof a duplicated column derivation and inform in the error message that the update failed because this transformation holds a duplicated column and you need to change it to refer to the group.

**Comment by tangrammer** [comment]
working in akvotest
<img width="1277" alt="Screen Shot 2019-12-16 at 16 12 15" src="https://user-images.githubusercontent.com/731829/70918225-14026e00-201f-11ea-8352-3ddcbea4ef1f.png">

**Comment by tangrammer** [comment]
also working in demo.akvolumen
getting the proper error with js transformations that should refer to the group to avoid data inconsistency references

![Screen Shot 2019-12-17 at 13 02 05](https://user-images.githubusercontent.com/731829/70994069-ab25ff00-20cd-11ea-816b-3e52b9a3cff8.png)
