### ISSUE TITLE
Docker development setup not working?

### ISSUE THREAD

**Issue by siemvaessen** [akvo/akvo-lumen#2568]
# Context
Followed the steps from https://github.com/akvo/akvo-lumen/blob/master/README.dev.md to run a local Lumen instance.

# Problem or idea
Did loads of downloading but after 20-30 mins (!) seems to go stale when webpack building basically stops.. I tried to access the locations (t1.lumen.local etc) but nothing there (not loading). 

# Solution or next step
Has this Docker compose recently been tested? I would like to run it and have a closer look :-) 

Thanks

**Comment by tangrammer** [comment]
Hi @siemvaessen! 

yep, docker-compose is the normal way that we at akvo use to start the development 

did you add your hosts entries?

also, could you paste here the (last) logs from docker-compose? it would be good if you include also those related with the webpack thing

thanks for giving a try to then lumen project!

**Comment by kardan** [comment]
Hey @siemvaessen it didn't happen to be so that you tried to build Lumen when npm had an issue? We pull packages from there and all our builds were broken for a little before it was fixed.  
Ref:
https://blog.npmjs.org/post/190932845330/incident-report-403-429-errors-for-some-usershttps://github.com/npm/cli/issues/836

**Comment by siemvaessen** [comment]
Thanks @tangrammer @kardan will give it another run soon~ish and report back.

**Comment by kardan** [comment]
Since we managed to build from scratch I'm closing this until we get feedback that the build is actually broken.
