### ISSUE TITLE
Improve pivot table UI to emphasize data

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#2768]
### Context
The idea is to improve the look and feel of pivot tables, based on pivot tables showcased in these dashboards: **Tableau de bord de suivi de la collecte** and **Tableau de bord des indicateurs du PARIIS** 

Notable improvements to consider:
1. Append aggregation method to end of aggregated indicator to prevent a twin-col-header. This is what we do with other visualizations but we break the pattern with pivot tables.
<img width="890" alt="Screenshot 2020-07-20 at 12 46 17" src="https://user-images.githubusercontent.com/12692444/87924138-23e7a200-ca87-11ea-972c-e500cdd6734f.png">

2. De-emphasizing borders and adding some spacing between data and borders to enhance data legibility.. 
3. Title case values, when source content is all caps, the table content is harder to read when it is all-capped as is evident in the snippet below
<img width="584" alt="Screenshot 2020-07-20 at 12 14 31" src="https://user-images.githubusercontent.com/12692444/87920948-999d3f00-ca82-11ea-897a-1a336568b655.png">

4. Wrap long col header and values - i.e. define a column width so that the resulting table is visually balanced; in the attached example, we have a couple of long values the accommodation of which makes the second column squeezed up 
<img width="597" alt="Screenshot 2020-07-20 at 12 10 45" src="https://user-images.githubusercontent.com/12692444/87921077-c3566600-ca82-11ea-8bfd-ce0acbc3c07d.png">
 
- when wrapping text in a row, align the values for adjoining rows to the middle (atm it is done to the bottom) this will add to the perceived visual balance;
<img width="548" alt="Screenshot 2020-07-20 at 15 18 07" src="https://user-images.githubusercontent.com/12692444/87936961-767f8900-ca9c-11ea-989e-487189fbc98d.png">

5. Stop truncating table content - even though we support mouseover as a way of revealing truncated text, this is not optimal; a dashboard is meant to be read or reveal patterns quickly, forcing the user to use mouseover to reveal values goes against the intention
<img width="597" alt="Screenshot 2020-07-20 at 12 10 45" src="https://user-images.githubusercontent.com/12692444/87920832-6eb2eb00-ca82-11ea-870c-a5c61f8a699a.png">

6. Add spaces between cascade item separators to make the resulting text more readable. This should also make it easier to wrap the text - This tweak might be more applicable at data importing level but the refinement will carry over to the grid and resuting visualizations
<img width="556" alt="Screenshot 2020-07-20 at 14 59 09" src="https://user-images.githubusercontent.com/12692444/87935436-cb6dd000-ca99-11ea-8584-5088c76a6f19.png">

7. Align the pivot table (in contrast to other types it is unique) to the left of the visualization container so that it takes use of full-container-width; centre-align also breaks the scannability (from the title to table content)
<img width="760" alt="Screenshot 2020-07-21 at 15 14 31" src="https://user-images.githubusercontent.com/12692444/88053842-21f41080-cb65-11ea-9927-e213e7c1b898.png">

8. It is not clear what a pivot table counts by default 🤔 this should be made explicit, otherwise result to a meaningful default/empty state
<img width="1387" alt="Screenshot 2020-07-21 at 15 40 09" src="https://user-images.githubusercontent.com/12692444/88056538-671a4180-cb69-11ea-830b-505aef2546f8.png">

**Comment by Kiarii** [comment]
On point 1: [Appending aggregation method to indicator name](https://www.figma.com/proto/XQtjy781ugZ8dmmaA9hWnO/Lumen-style-guide?node-id=328%3A6&scaling=min-zoom)
<img width="620" alt="Screenshot 2020-07-20 at 14 51 00" src="https://user-images.githubusercontent.com/12692444/87934816-839a7900-ca98-11ea-9aca-4eea4d692e95.png">

**Comment by janagombitova** [comment]
@Kiarii the twin column header is not because of the aggregation method but the first header holds the column title and the 2nd the text values of the selected column and `total count` if enabled:

<img width="1190" alt="Screen Shot 2020-07-20 at 14 37 34" src="https://user-images.githubusercontent.com/12456965/87938252-91e79580-ca96-11ea-85b7-cd8590b5a22d.png">

**Comment by Kiarii** [comment]
@janagombitova now I see your screenshot :) agree on the links posting matter, thanks for noting that. About your description of the pivot;

> ..the first header holds the column title and the 2nd the text values of the selected column..

It sounds more or less like a presentation of a MOQ data, in which case, even on the grid breaking the question and the responses i.e. creating a twin col header makes the resulting table/grid 'unbalanced'.. Looking into this..

**Comment by Kiarii** [comment]
on the data grid, as screenshoted below, we do not separate MOQ question from the response; in keeping the pattern (which I think is a low hanging fruit in contrast to inventing a new wheel) the challenge for pivot tables as for the grid is two fold: 
- How to accommodate long text values (mostly col headers) and 
- How to support the use of shorter versions of these either via using variable names or custom-user defined names (at least on visualizations)
<img width="819" alt="Screenshot 2020-07-21 at 13 55 06" src="https://user-images.githubusercontent.com/12692444/88047143-d4be7180-cb59-11ea-8702-b4a6a8b5558d.png">

**Comment by Kiarii** [comment]
at the least, (without supporting variable names or user defined col names) based on the example shared by @janagombitova above, we are looking at sth of this sort
<img width="1427" alt="Screenshot 2020-07-21 at 15 02 31" src="https://user-images.githubusercontent.com/12692444/88052655-3a632b80-cb63-11ea-9477-dff3b5749bb6.png">

**Comment by janagombitova** [comment]
I have summarised the visual improvements into the following list. I suggest we start here. Then the remaining issue is how to handle the double-header (column title and column values) that currently breaks the table layout. I suggest we discuss this one before making a decision on how to address it. Same goes for the twin-row due to `total`.  

# Pivot table initial improvements: 

* [ ] De-emphasizing borders and adding some spacing between data and borders to enhance data legibility  
* [ ] Define a column width so that the resulting table is visually balanced (currently the 1st column holding the row values is longer to accommodate the values, but results in the second column looking all squeezed up)
* [ ] Wrap long col header values and row values, so stop truncating table content
* [ ] Align data to the middle - When wrapping text in a row, align the values for adjoining rows to the middle (atm it is done to the bottom) 
* [ ] Left align col titles (for num data types we maintain a right alignment of values)
