### ISSUE TITLE
Improve how we show data labels in bar charts 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2818]
# Context
Bar charts are our most used visualisation type and the preferred way to analyse and show data. Thus our goal is to make these visualisations as understandable as possible. One of the elements of that is to make sure readers understand what each bar represents. 

# Problem 
However, this is an issue when labels are too long. We encourage our users to use short variable names, but sometimes labels are simply long. In this case, today we show a certain number of characters only. 

If Salim has long labels he tends to go for horizontal bars to be able to show more of the label, but here we again only show a certain number of characters. 

<img width="804" alt="Screen Shot 2020-08-17 at 13 50 26" src="https://user-images.githubusercontent.com/12456965/90393301-c13af380-e090-11ea-8dc1-6a5d490bc6f7.png">
<img width="825" alt="Screen Shot 2020-08-17 at 13 51 08" src="https://user-images.githubusercontent.com/12456965/90393304-c26c2080-e090-11ea-8efc-4dfa62852d84.png">

# Opportunity
The first request is to show labels on the x-axis always horizontally and wrapped and not diagonally as it is hard to read. 

The second request is to show the full label for horizontal bars, like for example here: 

<img width="501" alt="Screen Shot 2020-08-17 at 13 34 58" src="https://user-images.githubusercontent.com/12456965/90392595-753b7f00-e08f-11ea-91a2-081ac64e411d.png">

<img width="495" alt="Screen Shot 2020-08-17 at 13 34 22" src="https://user-images.githubusercontent.com/12456965/90392589-72d92500-e08f-11ea-9036-d5fba3910e59.png">

**Comment by kardan** [comment]
Update:
Been trying to look into this issue when I had some time. Turns out there is no official support for text wrap in svg 1.1 (the current). There are alternative solutions like 
- https://medium.com/@CarysMills/wrapping-svg-text-without-svg-2-ecbfb58f7ba4
- https://github.com/d3plus/d3plus-text
- https://gist.github.com/davelandry/a39f0c3fc52804ee859a

So far I been trying to integrate the d3plus-text library into our react world
