### ISSUE TITLE
Cannot change colours on scatter plots 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2945]
https://demo.akvolumen.org/visualisation/5f7ac727-381d-4b21-9384-7c28ea52a5bd

Steps to take to recreate: 
1. Select to create a new scatter plot. 
2. Define the x and y axis. 
3. Click on a point to change colour --> **does not work**
4. Define the category bucket - the points are now coloured based on the values. 
5. Click on a point to change colour --> **does not work**

**Comment by janagombitova** [comment]
@marvinkome what is the status of this issue?

**Comment by marvinkome** [comment]
It works when you select the category bucket column. But to support changing the default blue requires API changes. And also there's a bug when you create a new scatter plot the colors are not consistent with the label config. This is due to the way the scatter plot is created. I'd have to refactor for it to work.

**Comment by janagombitova** [comment]
Thanks Marvin for the update. Let's keep the issue open then for now and see how to plan things in once we finish the work on RQGs

**Comment by tangrammer** [comment]
Parking the issue a while until we found time to refactor this client related code 

Relates to https://github.com/akvo/akvo-lumen/issues/2979#issue-724525082
