### ISSUE TITLE
Update dataset walkthrough to inform about RQGs changes 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#3023]
Today when a user opens a dataset for the first time, she sees a walkthrough telling her that we changed the data grid to show data groups and walks her three more detailed steps. 

We feel the need to keep this walkthrough, but we need to adapt it to reflect the new reality once we support RQGs data. 

@Kiarii can you provide the mockups on how we want to update the walkthrough (the changed text and steps). 

Please note that this issue also relates to removing the option to `switch view` on the dataset grid that will be handled in a different issue.

**Comment by Kiarii** [comment]
A side note on the context to onboarding the Salim, Petra and co. to the new changes
- It is shown when they open a (Flow) dataset since the changes correspond to Flow data; splitting data by question groups and support for RQGs
- First comes the benefits modal, followed by
- The two step walkthrough (this should be properly redesigned as modals

See [prototype](https://www.figma.com/proto/XQtjy781ugZ8dmmaA9hWnO/Lumen-style-guide?node-id=1537%3A0&viewport=2616%2C1107%2C0.5&scaling=scale-down) for more details

**Comment by Kiarii** [comment]
The new call to focus on support for RQG means a number of things mainly:
- Remove the previous datagroup onboarder and consequent walkthroughs
- Remove the dataset view switcher
- define a context for show the RQG support benefits modal: a) to be shown once, b) when a user opens a dataset with RQGs, c) for now we've decided not to include a walkthrough and leave the user to figure out RQGs view and analysis..
