### ISSUE TITLE
Failed to fetch dataset when trying to derive category column 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#3055]
When trying to use `derive column - category column` transformation on this dataset https://asia.akvolumen.org/dataset/5f900278-f4bf-4100-9c69-d2be90a64561 I get the error `Failed to fetch dataset`. 

I tried on other instances and it worked fine.

![Screen Shot 2020-11-19 at 09 26 14](https://user-images.githubusercontent.com/12456965/99640531-4d223a00-2a49-11eb-8437-8f66489e4734.png)

**Comment by iperdomo** [comment]
What we have found so far:

* The problem is because the Dataset is based on a Flow form, 
* The form was imported
* One question was deleted from the form (in Flow)
* An *Update* to the Dataset has been done after that question was deleted
* An *Undo* has been done
  * It seems that we have some faulty logic to pick the right definition for the dataset columns. Instead of picking the columns **after** the update (that removed the question/column), we pick the **original** set of question that defines a non-existing one

We're still investigating and trying to reproduce the issue

**Comment by iperdomo** [comment]
The current workaround is to *Update* the dataset again, so we re-define the set of column definitions

**Comment by tangrammer** [comment]
reproduced locally the problem 
https://gist.github.com/tangrammer/d482de2fe4e9defae643e9ee0dc6bf0b

**Comment by tangrammer** [comment]
BTW: the issue is not specific to derive category column but to update and undo processes
