### ISSUE TITLE
Show full column name on hover

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#392]
Currently, the column name is abbreviated. This does not provide enough context in many cases. We need a way for the user to see the whole name. Perhaps hover?

<img width="208" alt="screen shot 2016-10-10 at 11 47 50" src="https://cloud.githubusercontent.com/assets/478954/19232323/67232f2c-8edf-11e6-9248-8fbf3e5dc759.png">

**Comment by gabemart** [comment]
I see two options for this -

## Option 1

Use the `title` attribute to show the full name on hover

![title-tooltip mov](https://cloud.githubusercontent.com/assets/2589977/19889135/17fc7d9c-a02b-11e6-9b9a-12d70de5f2c1.gif)

Advantages: 
* incredibly simple
* shows full column name
Disadvantages:
* there is a delay before browsers show the tooltip, and this cannot be changed
* No styling can be applied to the tooltip

## Option 2

Use a custom tooltip. Usually this is also very simple, but in this case due to issues with how the grid component deals with overflow, it is not simple in this case.

![custom-tooltip mov](https://cloud.githubusercontent.com/assets/2589977/19889253/c9a4635c-a02b-11e6-8215-6752f59dff93.gif)

Advantages:
* tooltip appears immediately
* can be styled arbitrarily

Disadvantages:
* due to the overflow issues, the tooltip has to be sized "manually", so contents can still be clipped in some cases, and bounding box can be too large in other cases

---

I'm really leaning towards using the `title` attribute, does this seem acceptable @mtwestra?

**Comment by mtwestra** [comment]
@gabemart, I think your proposed solution 1 is fine, i don't think the delay will be an issue. It feels natural to me. If during later user testing it is an issue, we can always revisit this, but I don't expect it will be needed.
