### ISSUE TITLE
X axis title clashes with other labels

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#394]
The X axis title clashes with other labels when the labels are long (vertical).

<img width="835" alt="screen shot 2016-10-10 at 12 03 57" src="https://cloud.githubusercontent.com/assets/478954/19232731/abc22a28-8ee1-11e6-94b5-787a660f5efe.png">

**Comment by gabemart** [comment]
Additionally:

Currently, x axis labels are cut off on the graphs.

![image](https://cloud.githubusercontent.com/assets/2589977/19894624/927a7ab4-a045-11e6-8666-1d303b807f63.png)

**Comment by gabemart** [comment]
I adjusted the code that generates the vega spec to find the longest label, work out its approximate length (in pixels), then adjust the padding and size of the chart so that x-axis labels never overlap column labels, and column labels aren't cut off at the end of the canvas

However, because there is no hard limit on the length of a column label, we need some kind of max on how long a label we display, otherwise a long column label will take up the entire height of the chart. I've set this limit at 32 characters for now, but it's a one-line change to adjust it if 32 feels to big or too small. Labels longer than the limit are truncated with "..." as in indicator (as can be seen in this gif)

![labels mov](https://cloud.githubusercontent.com/assets/2589977/19937300/9426d9a6-a118-11e6-8060-926b28eeffaa.gif)

**Comment by mtwestra** [comment]
@gabemart, I found a nice solution in another tool: 

<img width="714" alt="screen shot 2016-11-04 at 12 02 55" src="https://cloud.githubusercontent.com/assets/478954/20003527/37b462cc-a287-11e6-8260-5d270589f6d4.png">
So basically you show the start of the string from the bottom, and cut off at some length. Using hoover, the whole string is shown
