### ISSUE TITLE
'Copied!' message even though dashboard link not copied (Safari)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#507]
# Context
There is an option to share a dashboard via a link.
When one clicks on the link, the following dialogue appears:
<img width="754" alt="screen shot 2017-01-17 at 13 40 52" src="https://cloud.githubusercontent.com/assets/21127166/22020846/9e83627e-dcba-11e6-8c82-9d8c2bf39c1f.png">

# Problem or idea
What is the cause?

After copying the link using the prompt, one get's 'Copied!' message even though the link wasn't copied. 

# Solution or next step
How could we solve it?

Apparently Safari restricts copying to clip board, so we either need to find a workaround or rework the workflow to avoid displaying 'Copied!' to the user.

**Comment by gabemart** [comment]
When Safari 10 is released, apparently it will support copying to the clipboard via `document.execCommand('copy')`, which is good news (auto-copy will work if that's true)

In the mean time, we should detect if the user has been shown the fallback modal - if they have, we shouldn't update the text of the "Copy" button to read "Copied" (because we don't know that the user has copied the text from the fallback modal)

We should also see if it's possible to display some more helpful text in the fallback modal - something like "Copying to clipboard failed, please copy the link manually"

**Comment by finnfiddle** [comment]
closing because an old issue and I cant reproduce
