### ISSUE TITLE
Stacked bar chart - bar oversteps on the title

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#508]
# Context
Stacked bar chart allows building graphs with 'sub-buckets' for each bar.

# Problem or idea
One of the tallest stacked bars oversteps on the title of the graph:

<img width="1087" alt="screen shot 2017-01-18 at 10 17 30" src="https://cloud.githubusercontent.com/assets/21127166/22058466/3ae38f82-dd69-11e6-8058-dc20836429b9.png">

When we do stacked-bar-chart, for technical reasons vega doesn't know how high to make the chart, so we explicitly set a height, which we calculate by adding together the biggest sub-buckets.

# Solution or next step
How could we solve it?

Create more space for the graph's title

**Comment by gabemart** [comment]
It turns out that the system was calculating the height of the highest stacked-bar correctly when using "count" as the aggregation method, but incorrectly when using any other aggregation method. 

I've created a PR to fix this - it's definitely a bug - but it's might be worth noting that I find it hard to think of any valid use case for a stacked bar chart using an aggregation method other than count.

**Comment by gabemart** [comment]
closed via #521
