### ISSUE TITLE
Repeated question group support (design)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#529]
# Context
We need to support Flow data with repeated question groups. 

# Problem or idea
What is the cause?

# Solution or next step
We should probably also research weather the grid element we currently use will work with repeated question groups: https://github.com/akvo/akvo-lumen/issues/691

**Comment by Kiarii** [comment]
Have started exploratory work on this one; my first take is on summarizing RGQ responses so that users can make sense of an Indicator's responses easily; it will also be sth to explore further with users to figure out what sort of breakdown would make the Summary meaningful (if this is helpful at all)

![image](https://cloud.githubusercontent.com/assets/12692444/25744653/bd227ac4-31a3-11e7-97a9-afe495d190ad.png)

**Comment by kardan** [comment]
Should this issue have the "in progress" label?

**Comment by Kiarii** [comment]
@kardan am not aware of the commencement of any related work; maybe Nadia knows, or is it in the roadmap?

**Comment by nadiagorchakova** [comment]
We added 'dataset redesign without the data grid' into our 2018 roadmap. However, Gabe, Daniel and I agreed that it depends on whether we're going to have time for it or not. 'Summarizing RGQ responses' as per Kiarii's design can only be done after we do the switch. So to conclude, it's not really 'in progress' at the moment.
