### ISSUE TITLE
Custom range for axes

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#590]
### Context
Currently, the range of numerical axes is determined automatically, from the range of actual values a graph. In some cases this is fine, but in other cases, users need more control over what is shown. For example:
* When the range of values doesn't include zero, but you want a graph to start with zero
* When there are multiple plots and you want all of them to have the same y-scale, so they are easier to compare

### Proposed solution
Proposed solution is to let users edit the scale of an axes, so custom values can be provided.

**Comment by finnfiddle** [comment]
closing because this looks like it's fixed

**Comment by janagombitova** [comment]
Today I spoke with a user from IUCN requesting the same. 

# What is the current status quo?
She said they analyse all their indicators by comparing men and women. So they have two graphs, identical, per indicator in dashboards next to each other. But because the values for men and women can differ reading the graphs is harder. 

For example, You compare different training topics and how many women and men attended which training. At first glance, the same number of men and women attended the Agricultural track as the bars look the same size, but actually, the number of women is triple the size of men. 

# If the change is successful what might we observe? 
- we could see more dashboard shares and views as the visualisations created will be more readable, thus Salim will feel more comfortable in sharing them 
- we could also see more visualisations as Salim will explore what other things he can compare 

# How could we solve it?
A solution can be to allow the user to define the scale for the y or x-axis themselves. 

The question that we would also need to address is what to do if new data comes in that does not fit the set range? 

# Whose behaviours will change and how?
Salim's behaviour will change as he will have to put more effort into creating the visualisations. He will need to know that he is working on two visuals that compare the same values for different categories. He will need to remember the axis set up he did on one and create the same on the other. 

Petra's life, on the other hand, will be simplified as she can scan through the visualisations on a dashboard and quickly understand the situation. She will not need to pay attention to the details as the axis set up will be the same making comparisons easier to see and do. 

# How will this new behaviour benefit users?
- easier to understand what the visualisations are telling
- more conscious decisions around analysing and working with data that can result in the better survey set up thus making the entire data process eventually more efficient 

# How will this benefit Akvo? 
- will make Lumen a more professional visualisation tool, thus easier to sell and pitch
- can support is our services around advising how to best analyse data and visualise data
