### ISSUE TITLE
Dashboards - don't close dashboard when user clicks 'Save'

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#618]
### Context
Currently, when a user edits a dashboard and clicks 'save', the dashboard is closed and the user is returned to the library. 

However, this behaviour is not consistent with when a user clicks 'save' when editing a visualisation, in which case the user remains in the visualisation edit window.

### Proposed solution
Proposed solution is to use same behaviour as visualisation, and not close the dashboard after clicking 'save'.

**Comment by gabemart** [comment]
In order to give some feedback to the user that the save action has been performed, we should also show the save status in the header, as we do for visualisations - e.g.

![image](https://cloud.githubusercontent.com/assets/2589977/23614422/c0d02b74-027a-11e7-88c4-fd736515524d.png)

![image](https://cloud.githubusercontent.com/assets/2589977/23614454/d933897c-027a-11e7-8389-c241039271d1.png)

**Comment by mtwestra** [comment]
@gabe, yes, this make sense indeed.
