### ISSUE TITLE
Unshare functionality

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#665]
# Context
Lumen users can share visualisations and dashboards to the public.

# Problem or idea
Once shared, there is no way to unshare. There should be a way to remove shared items from the public.

# Solution or next step
When an item is shared we could hide the share button and instead show a "Unshare". Maybe we should even show in the library that something is public or not.

**Comment by janagombitova** [comment]
Also reported by Joy: https://flowhelp.reamaze.com/admin/conversations/feature-request-unpublished-a-dashboard

Use case: I create a dashboard and share the link with a bunch of people.
A few days later I notice errors in the dashboard that i cannot immediately fix for various reason. I cannot stop people from accessing the dashboard. I want an “Unpublished” functionality so that I can de-activate a dashboard.
