### ISSUE TITLE
Scoring transformation

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#671]
# Context

See product and design repo for the upcoming mockup: https://github.com/akvo/akvo-product-design/issues/255

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
As I was trying to update the description and it did not work, I am adding the notes here: 

During our user story mapping session on scoring with Lumen dev team and @Kiarii, we came up with the following provisional workflow that still needs to be verified and refined:

<img width="1021" alt="screen shot 2017-03-27 at 18 25 34" src="https://cloud.githubusercontent.com/assets/21127166/24366876/d13ac946-131a-11e7-8c49-e54aec3054c6.png">

The full story mapping board with definitions, user problems and a provisional solution can be found here: https://app.mural.ly/invitation/mural/akvo8194/1488544015508?sender=loic4416&key=557173498

**Comment by janagombitova** [comment]
Another related and duplicated issue here: https://github.com/akvo/akvo-lumen/issues/527

**Comment by janagombitova** [comment]
When researching scoring we looked at different scoring formulas our partners use today [add expample] and tried to understand what are the steps they do in preparing the data, what do the formulas consist of, where are the pain points and what is the value of such formulas. 

We learned that usually scoring is done to conclude something about the subject of your data collection. For example, based on answers to these questions is the child malnourished or not, or does the farmer comply to a sustainability standard. Another example is calculating indicators, so again by looking at a set of questions where does the project stand in terms of their overall goals. 

To achieve this, text columns are assigned points and these are then summed to an end result and the end result falls into a category. For example, for the question 'How often did this happen?' there are three given options and each option has a value assigned to it. '1=Rarely (once or twice in the past four weeks), 2=Sometimes (three to ten times in the past four weeks), 3=Often (more than ten times in the past four weeks)'. 


So scoring usually uses more than one variable = column, calculates these variables and results in a number that is then categorised. There are also cases where the formula rather than being based on a calculation only, combined a sum (AND) and OR rules.

**Comment by janagombitova** [comment]
We have released the full implementation of the **Category column**. With this transformation, Salim can now derive a new column from a TEXT or a NUMBER column and the result column will be a TEXT column. This, however, does not stop Salim to add numbers as the new categories and then change the column type with another transformation to NUMBER. 

Considering this workaround I decided to close this issue. We will keep an eye out for the category columns created to see if users use it to assign points or do they still use the Derived javascript transformation. If the second, then we can reopen this issue.
