### ISSUE TITLE
PRICING - show resource usage in admin panel 

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#673]
# Context

Lumen pricing model is comprised of several pricing tiers with different access to Lumen resources.

https://peak.akvo.org/pricing-akvo-lumen-march-2017/

# Problem or idea

As a first step towards implementing pricing tiers, we will display resource usage in tenant's admin panel. Admin users can then communicate internally inside the team how much resources they have used. 

# Solution or next step

Usage section should display the name of the plan and how many resources the tenant has used already.

Board from our workshop: https://app.mural.ly/invitation/mural/akvo8194/1491548589404?sender=nadezda6240&key=2425247256

<img width="969" alt="screen shot 2017-04-07 at 12 23 45" src="https://cloud.githubusercontent.com/assets/21127166/24796396/17314298-1b8d-11e7-8a4e-58a24123de97.png">

The next step would be to show usage metrics also inside each resource, e.g. visualisation or dataset.
In can be on the side bar, not too disruptive.

**Comment by nadiagorchakova** [comment]
We'll focus on the 1st Tier for flow users, for the start

**Comment by kardan** [comment]
Definitions:
- tier, a named entity (lite, standard, pro, enterprise)
- plan, what tier the tenant is on, this can change over time (e.g. start as lite and then later promoted to standard)
- policy, restriction points (data updates, number of visualisations)
- tier policy (auto or manual for data updates, an integer for max number of visualisations)

This has nothing to do with billing for plans. We should not tie plans to billing tightly since we will run into a lot of corner cases regarding plan/billing period ends and changes between tiers. This work focus on stating what tier a tenant is on and also reporting the history (the tenant was standard between dates and then became pro between dates..) This allows billing functions to be build on top of this later.

**Comment by kardan** [comment]
In this branch the admin section have been refactored to have it's own nav menu. You switch between the different modes (admin, workspace) with the bottom button in the nav bar. A new "admin/resources" page has been add that renders a very crude (no styling) page shows something like: 
```
Tier: Standard 
Policy, Current, Limit
Number of visualisations, 1, 10 
```
This page is only shown in the admin but it's not protected for non admin. This since I guess we need the resources info in the workspace to.

There is a akvo/lumen/admin/add_plan.clj script to add plans to a tenant, but it only works on localhost at the moment.

Todo:
- [ ] Extend add-tenant script to also add a plan to the tenant.
- [ ] Extend add-plan script to work against non localhost (So we can change a tenant once it's setup)
- [ ] Design & style the resources page.
- [ ] Tweak the admin nav bar, at things like the top slide button exists but are disabled.

**Comment by kardan** [comment]
Todo:
- [ ] Fix issue where limits are not shown in the admin
- [ ] Make the new plan script use db from env vars
- [ ] Clean up tenant 012 migration
- [ ] Clean up code
