### ISSUE TITLE
Long column names overlap in map editor

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#688]
# Context
The pop-up tab in the map editor gives a choice of columns to be displayed in a pop-up

# Problem or idea
If the column name is long, column names appear overlapped. It makes them unreadable.

<img width="1276" alt="screen shot 2017-04-11 at 14 14 39" src="https://cloud.githubusercontent.com/assets/21127166/24908766/a2aaad00-1ec1-11e7-92a9-368446f2580a.png">

<img width="1255" alt="screen shot 2017-04-11 at 14 26 00" src="https://cloud.githubusercontent.com/assets/21127166/24909079/d48e8b92-1ec2-11e7-9cbc-550a5851a0b0.png">

**Comment by nadiagorchakova** [comment]
Jonas mentioned that long title problem is a recurring issue in Lumen.
We had a chat with Gabe and Jonas and had a few ideas about how we could improve that:

- maybe we could have both a column title and an optional column “description. Allow user an option to create descriptions for long columns during Flow import. 
- have a notification in the grid, when column title exceeds certain number of characters? 'Please shorten the title' or something like that. This way we moving towards a more assistive UI.
- display long titles on hover everywhere in Lumen.

In the end we thought would be great to hear @Kiarii's thoughts on that. Perhaps there are other more elegant solutions we didn't think of.

**Comment by jonase** [comment]
The problem is most evident for datasets derived from Flow surveys. Simply because the only column title we can derive is the question text, which tends to often be very long (and also descriptive).

Datasets from "ordinary" csv's tend to have much shorter column titles.

**Comment by Kiarii** [comment]
my feeling is that (for simplicity) we shd keep the original col titles (questions' texts); this also highlights the need to rethink data view.. based on the attached screenshots, we shd do 2 or 3 lines per col title and truncate the rest - make it viewable on mouseover, for example.. 

Also looking at how the scoring examples that we have, users are using the full question to refer to cols, so adding descriptions would add an extra layer of data, and confusion - given that flow questions contain description fields - not sure if these are being imported to Lumen or how they are being handled..

Another factor to consider is the 1-1 match between survey questions text and data cols' titles; this I think is important especially if a back and forth review is made by users 

i think this is also a question of training users how to name questions precisely and concisely so that the resulting cols names are not too long - something that we shd liase and communicate to the partner teams

**Comment by loicsans** [comment]
Agreed with Kiarii
