### ISSUE TITLE
Define Dashboard Canvas Behavior

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#703]
# context
After 2 rounds of story mapping, we had a number of questions which needed extra input from users so we made a survey to follow up and are now awaiting data from a survey that we have sent to pontential users to understand their current presentation needs and practices

**Comment by nadiagorchakova** [comment]
I would also like to ask you to review the UI/design of dashboards.
Example: https://demo.akvolumen.org/s/m2mIkD2XZcA

<img width="690" alt="screen shot 2017-05-01 at 16 21 16" src="https://cloud.githubusercontent.com/assets/21127166/25624310/40f8bf0e-2f59-11e7-8ceb-81e650b0a427.png">

For example, how to better integrate text (narrative) into dashboards? What's the best way to use spacing between different elements?, etc.

**Comment by gabemart** [comment]
On the topic of dashboards, I think one really important question to think about is how to render dashboards at different sizes?

In the dashboard editor, users use the **relative position** of entities to indicate relationships between those entities. For example, a user might position a text box close to a bar chart, to indicate that the content of a text box describes that bar chart.

But how can we preserve those relationships on viewport sizes that force us to **change the relative position of the entities** in order to fit the entities on the viewport? In particular, on small viewports, if we try to maintain the relative position of the dashboard entities, we would be forced to render them at such a small size that they would be illegible. On phone-sized viewports, we currently resize all entities in a single vertical column where each entity spans the full width of the column (so that we can show each entity at as large a size as possible). But this breaks relative-position-relationships.

For example:

![image](https://cloud.githubusercontent.com/assets/2589977/25800577/d496e470-33e1-11e7-8a4e-1799c7f16827.png)

When this dashboard is rendered at full-size (i.e. the size we use in the dashboard editor), it's fairly clear from the relative positions of the entities that the "well types" text entity applies to "Chart 1", and that the "acronym" text entity applies to "Chart 2".

However, under the current system, on smaller viewports, the way in which we resize the dashboard breaks these relationships:

![image](https://cloud.githubusercontent.com/assets/2589977/25800697/47a1cc32-33e2-11e7-8146-19b89649a1c6.png)

It now looks as if the "acronym" text entity refers to "Chart 1". 

This is a hard problem, because there is a virtually unlimited number of relative position combinations that a user might use on a full-sized dashboard to indicate relationships between entities. We can't detect all of them, and even attempting to detect a subset is a huge challenge.

**Comment by nadiagorchakova** [comment]
The Title element works differently in datasets, visualisations and dashboards. Maybe we could look into unifying it?

Datasets: The title is given at import stage, it's not possible to edit when inside the dataset (or anywhere else)

<img width="902" alt="screen shot 2017-05-11 at 15 50 53" src="https://cloud.githubusercontent.com/assets/21127166/25952724/ba63cf96-3661-11e7-85f0-96f7c96c8514.png">

Visualisation: It's possible to edit the title when in the visualisations editor

<img width="1090" alt="screen shot 2017-05-11 at 15 53 04" src="https://cloud.githubusercontent.com/assets/21127166/25953458/be12e620-3663-11e7-922d-8b350ecfada1.png">

Dashboard: It's possible to edit the title when in the dashboard editor but in a different place, compared to the visualisations editor

<img width="1269" alt="screen shot 2017-05-11 at 16 08 41" src="https://cloud.githubusercontent.com/assets/21127166/25953594/2bd03924-3664-11e7-8cdf-b9654bfcbbf1.png">

**Comment by Kiarii** [comment]
_Bulk action menu on the Library Should be a floating item_; it doesnt show if the user scrolls so that the top menu also goes out of view. The menu shd pop out in a way that is noticeable: atm since it assumes no background or color it is difficult to notice

![image](https://cloud.githubusercontent.com/assets/12692444/26357982/b8985002-3fd9-11e7-8afe-c222a51e65ef.png)


_Action / Event notification _ as long as it is not critical could take the form of https://material.io/guidelines/components/snackbars-toasts.html (desktop) ;  a bottom placement would also mean that both the bulk selection menu and its action events can be shown on the same location

![image](https://cloud.githubusercontent.com/assets/12692444/26357883/6678e408-3fd9-11e7-89f1-85e0744e880f.png)

**Comment by loicsans** [comment]
Priority: 10
Effort: 10

**Comment by Kiarii** [comment]
Based on our storymap: https://app.mural.ly/t/akvo8194/m/akvo8194/1499331641109 here are some wireframe mockups capturing the basic ideas for the canvas and adding objects onto it: https://invis.io/9TCLA2ORF#/243786916_0-_Empty_State
