### ISSUE TITLE
Login process goes into a loop when disabling third-party cookies

### ISSUE THREAD

**Issue by bjelkeman** [akvo/akvo-lumen#732]
# Context
When login in to Lumen certain cookies are set by Keycloak/Lumen. In Safari, if you disable third-party cookies, then you get a loop where Keycloak sends you to Lumen and Lumen sends you back to Keycloak. 

# Problem or idea
Set this preference to observe the behaviour: Safari->Preferences->Privacy->Cookies and website data
**"Allow from current website only."**

Strangely enough it seems to work correctly to have **"Always block."** on. (At least when already logged in and changing to "Always block". If you are already logged in and set to "Allow from current website only". Then after a few UI interactions you are back to the looping behaviour.

It works correctly with third party cookies set to  **"Allow from websites I visit."**

# Solution or next step

Investigate if we can have a less disconcerting behaviour and a useful error message for the user.

**Comment by iperdomo** [comment]
As mentioned in the development chat, this is not a Safari specific issue. Every user with _privacy concerns_ will disable 3rd party cookies (Firefox and Chrome also has this option).

https://support.mozilla.org/en-US/kb/disable-third-party-cookies
https://support.google.com/chrome/answer/95647

The issue is that the client side code is handling the authentication and session state. If we move to a backend based authentication/session (_plain old fashioned_ way of handling sessions) this issue goes away.

**Comment by gabemart** [comment]
There is an existing issue for this at #694 

There is more discussion here, so I will merge #694 into this issue

**Comment by iperdomo** [comment]
> __We don't need lumen to work with third-party cookies disabled (though of course that would be nice, if it were possible)__. 

_Interesting_ statement and trade-off.
