### ISSUE TITLE
Simplify column selection in Derive column - javascript

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#742]
# Context

At Lumen product meeting, I received a suggestion on derived column expression builder.
Writing expressions for derived column requires mentioning full column names. In some cases column names are quite long (a survey question). Often you cannot rename or shorten it because the column name is data on its own - if you shorten it, it might loose some of its meaning. 

An example of a long column name:

<img width="298" alt="screen shot 2017-05-19 at 09 24 40" src="https://cloud.githubusercontent.com/assets/21127166/26237350/1081347c-3c75-11e7-980d-462a632a84f8.png">

# Problem or idea

The suggestion was to give user an option to copy paste column names into Javascript code field. It would save users a lot of time and effort and encourage more of derived column use.

**Comment by jonase** [comment]
I would like to explore "auto-complete". So when you write `row[` you would get a list of suggestions of the available columns and you simply pick the one you want from the list. I think this should be possible with the code editor we're using [CodeMirror](https://codemirror.net/). If we could get this working I think it would be superior to copy/paste.

**Comment by nadiagorchakova** [comment]
@jonase if the number of columns is > 10, would presenting user with suggestions still be feasible? (especially lists)

**Comment by janagombitova** [comment]
We are experiencing more and more issues with updating datasets because a column is missing but used in a transformation. When investigating the issue further, we learned that already when creating a derived-javascript transformation defining the column properly is hard and very mistake-prone.

This issue started out as a simple copy-paste idea but the suggestion from Jonas on making it easy to select the column you want to derive your column from would be the easiest way for us to ensure the right column is defined. 

How we should handle this is unknown, maybe there are more solutions besides the one suggested here. But the problem that we are trying to solve is: **How might we ensure the column is well defined when using the derive column-javascript transformation?**

**Comment by tangrammer** [comment]
I like the `auto-complete ` approach mentioned here https://github.com/akvo/akvo-lumen/issues/742#issuecomment-302662855

**Comment by janagombitova** [comment]
Another related issue requested by Molo via support: https://flowhelp.reamaze.com/admin/conversations/akvolumen-support-request-number-383796-from-andrew-at-akvo-dot-org

> In the data view section, I'd like to group specific columns that I want to work with. For example If I want to derive a new column JavaScript code and the data has 20 columns, I have to scroll back and forth between the columns so as I dont miss out anything.
