### ISSUE TITLE
Go [Back] or reveal [Menu]?

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#777]
# Context
Why do we add this issue?

# Problem
When in an Asset Viewing/Editing screen, should we provide the [Menu] as we do currently? Or should we provide the [Back] button so the user can jump back to their (source) Collection/Library?

![image](https://cloud.githubusercontent.com/assets/12692444/26554676/296dd1f2-449a-11e7-8bc5-dd7b73d92d00.png)
 

# Proposal
It seems that the [Back] button would make more sense, in the assumption that the user is working from a Collection or Library to which it would make sense to go back to, instead of having to reveal the Menu in order to go back.. 
If we are in agreement we could proceed thus..?

**Comment by loicsans** [comment]
Implement a back button when editing an entity.
Priority: 10
Effort: 4

**Comment by gabemart** [comment]
There seems to be a consensus around removing the collapsing element of the sidebar menu entirely

**Comment by gabemart** [comment]
@Kiarii @loicsans I made these changes to test out, and my only concern is that when the user is in the visualisation editor, it might not be immediately clear what "back" does, because it feels as if they are "two levels deep".

When the user creates a new visualisation, they first see this page:

![image](https://user-images.githubusercontent.com/2589977/27445134-a1348a1c-5770-11e7-90fd-36e27f362348.png)

Then, after selecting a new visualisation, they are in the editor:

![image](https://user-images.githubusercontent.com/2589977/27445164-b5adac12-5770-11e7-92c1-5dbe46ec5bf5.png)

At this point, they might expect the back button to take them to the "choose a visualisation" page, rather than the Library view.

So what do you think should happen? I guess it's a question of if the button works more like a "back" button or more like a "home" button

(Currently, using the real browser back button in the visualisation editor takes the user back to the library view, skipping the "choose visualisation" view)

**Comment by loicsans** [comment]
I assume we can close this for now

**Comment by Kiarii** [comment]
I guess for the first go, it suffices for the [back] icon to act as a [homepage]..
