### ISSUE TITLE
Enhancements on CSV file upload screen

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#80]
- [x] Include a progress bar of the upload process
- [ ] Include a section with the CSV settings
  - [ ] File encoding
  - [ ] Skip [n] lines
  - [ ] Text qualifier / Text delimiter

**Comment by jonase** [comment]
@iperdomo 

* With https://github.com/akvo/akvo-dash/issues/81 the user wouldn't need to specify the encoding since we try to solve it by using apache tika
* Should we add something like "Treat first row as column names"? If not we might want to add a transformation like "Extract first row as column names" and change the current default behaviour.
* Right now we have `Data file` and `Link` data sources. Should we unify these two into a single "CSV" data source where you either upload a file or provide a link. One problem with this would be that a link can potentially support periodic updates while a file upload can't. 
* If we treat Link and Upload as two different data sources perhaps the user needs to specify file type (only csv for now) and only show csv specific options when the file type has been selected. Or should we have more specific data sources like "CSV Link" and "CSV Upload"?

**Comment by iperdomo** [comment]
> With #81 the user wouldn't need to specify the encoding since we try to solve it by using apache tika

Agree. I think we should detect it

> Should we add something like "Treat first row as column names"? If not we might want to add a transformation like "Extract first row as column names" and change the current default behaviour.

Let's agree on this based on @Kiarii input

> Right now we have Data file and Link data sources. Should we unify these two into a single "CSV" data source where you either upload a file or provide a link. One problem with this would be that a link can potentially support periodic updates while a file upload can't.

I think we want to keep them separate but _re-label_ the titles to "CSV [...]"

> If we treat Link and Upload as two different data sources perhaps the user needs to specify file type (only csv for now) and only show csv specific options when the file type has been selected. Or should we have more specific data sources like "CSV Link" and "CSV Upload"?

For now we should restrict to only CSV. In the case of the `file` input, we can use the `accept` attribute. https://www.w3.org/TR/html-markup/input.file.html#input.file.attrs.accept

In the case of the link we need to download the file and check the mime type with Tika, if is `text/csv` we process it.

**Comment by iperdomo** [comment]
I made a sample test downloading a CSV file from http://api.worldbank.org/v2/en/indicator/BN.CAB.XOKA.CD?downloadformat=csv and using Tika, detect the mime type.

````
(def tika (Tika.))                                                                                                                                              
(.detect tika (io/file (io/resource "Metadata_Country_f6f5bae3-a943-4bb9-ae2f-cea3695836ea_v2.csv"))) 
;;=> "text/csv"  
````

**Comment by jonase** [comment]
Let's open more specific issues based on user feedback. Closing
