### ISSUE TITLE
Give option to chose Flow variable names (question IDs) as column title

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#964]
# Context

Flow supports two ways of exporting data: (1) a dataset with all the raw data, (2) a more structured dataset. If a user picks (2), dataset columns will have question IDs as titles instead of full survey questions and cascade questions will be split into separate columns. 

By default, Lumen takes full survey questions as column titles during Flow form import. Flow API doesn't account for question IDs either.
 
# Problem or idea

Karolina and Jana mentioned that some Flow survey questions are really long, therefore, it might be challenging to work with them in Lumen dataset editor or visualisations editor.

**There is, however, a philosophical question of how deep we want Flow-Lumen integration to be.** 

A suggestion from their side was to allow Lumen users to choose whether they want to pull question IDs or full question text as a column title. Probably, this option should be given as an additional step during Flow form import. 

To enable that we at least need to:
- enable question IDs in Flow API. Jana created an issue for that: https://github.com/akvo/akvo-flow-api/issues/89
- implement changes to Flow Import UI.

# Solution or next step

**Comment by jonase** [comment]
I discussed this briefly with Jana last week and I fully agree we should implement this.

**Comment by janagombitova** [comment]
Just a small update on this issue. 

We have decided to change the name of the "question ID" to "variable name". If implemented in Lumen to use this element in column headers we should use the same naming to have consistency across the tools. 

Issue on name change: https://github.com/akvo/akvo-flow/issues/2170
Issue on adding to API: https://github.com/akvo/akvo-flow-api/issues/89

**Comment by janagombitova** [comment]
As part of our goal to streamline the connection between Flow and Lumen this issue is no longer a maybe, but a To do. The value of variable names sits in the fact that it makes analysis easier. Instead of working with long column names, Jerome works with short variable names that better define the data in the column. 

The variable names are defined with the survey form set up. Once Petra, Jerome or Salim create the survey, they also while defining the question text also immediately define the variable names. This is because they define the datatype and how the data will be collected thus thinking of how it will be analysed as well in that moment of time. 

The variable names are however **optional** thus not each dataset will have these defined.

The variable names are visible and used at the moment of transforming and working with the dataset.  In Flow the Data Analysis export uses the variable names as column headers. When working with the data in Excel it is easier to analyse as the column headers are brief and unique. 

The expectation is that Jerome can work with these also in Lumen when handling the data.
