### ISSUE TITLE
Flow monitoring support (design phase)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#965]
# Context

@janagombitova and @Kiarii did user research on Flow data export and we believe some of the findings could be applied to Flow monitoring support in Lumen. Here are the highlights that Jana shared with me.

Assumption:
An organisation has a registration form and at least two monitoring forms. Example:

<img width="675" alt="screen shot 2017-07-19 at 11 45 57" src="https://user-images.githubusercontent.com/21127166/28361148-1b991748-6c78-11e7-87fd-6f411d85135c.png">

There are two main cases of how Flow Monitoring data might be used:

1. Flow monitoring form is used to collect data on multiple occasions over time. The last monitoring submission for each data point is added to the registration form dataset as additional columns. Data merged in this way is then analysed. 

Example of Case 1:

<img width="1068" alt="screen shot 2017-07-19 at 11 48 11" src="https://user-images.githubusercontent.com/21127166/28361165-323f6740-6c78-11e7-8c21-44f505b60b36.png">

2. Flow monitoring form is used to collect baseline value and later - 'actual value' to monitor progress over time using these two points in time. _Some_ registration form data is added as additional column(s) to the Monitoring dataset. Data merged in this way is then analysed. 

Example of Case 2:

<img width="798" alt="screen shot 2017-07-19 at 11 49 15" src="https://user-images.githubusercontent.com/21127166/28361195-5b6d4dd0-6c78-11e7-98ec-97cd64219578.png">

When talking with Mark, he mentioned another case he believes is valid. Monitoring data collected over multiple occasions is aggregated in a single derived column which is added to the Registration form as an additional column.

This idea was not voiced by interviewed Flow users so far.
Limitations: (1) only numeric data can be aggregated;  (2) aggregated values cannot be used to monitor change over time.

Example: 

<img width="992" alt="screen shot 2017-07-19 at 11 50 16" src="https://user-images.githubusercontent.com/21127166/28361240-7a3ebd66-6c78-11e7-88b8-afc4f4b7c336.png">

# Solution or next step
Jana identified three Flow users that we could validate our ideas with:

Water for people, World Vegetable Centre and a partner from Asia (tbc)

Related issue on merging datasets: https://github.com/akvo/akvo-product-design/issues/260

**Comment by janagombitova** [comment]
Today we spoke with @nadiagorchakova and @Kiarii on what we know already about monitoring in Flow and how to proceed on this issue. We agreed to: 
- Share examples of monitoring cases currently in Flow to get a better feeling of how the data actually looks like and what users can do when working with the data
- Identify actions users do when they analyse monitoring data. 
   - From the research done up till now we know of some actions users to when working with monitoring data, but we want to do two more interviews with Akvo's M&E experts to list down the actions. 
   - We can also talk about items as: What would ideal workflow be? What were the complications when working with monitoring data? Tools they use?  
   - Nadia mentioned we need to keep the interview focused on what user do to prepare the data for analysis, as for example computing a score from the data falls under a different issue. We agreed that by asking our users what steps they take since the moment they receive the raw data till the moment they are ready for analysis will keep the discussion focused.
- Story map
- With the identified Flow users validate the proposed solution prototype

**Comment by nadiagorchakova** [comment]
A board from user story mapping sessions: https://app.mural.ly/t/akvo8194/m/akvo8194/1501759736997/62df02a66d3e0c1bad89d66708945fbe3c5ead08

An initial mockup for one of the suggested solutions: https://projects.invisionapp.com/share/WSCZC82F5#/screens/247997026_0-_Lib

We're now going through the story board together with Lars as the issue touches on Flow Lumen integration strategy as well.

**Comment by nadiagorchakova** [comment]
A story map board we explored merge as a more generic feature (not Flow specific)
https://app.mural.ly/t/akvo8194/m/akvo8194/1503472104657/90ce6dacb7630298a4cbce9e809d4b6efdbf9db9

tbc
