### ISSUE TITLE
Support editing an existing transformation

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#978]
# Context
when a derived col is created, provide the ability to re-edit the formula to change the outcome

# idea / next step?
- provide button e.g. "edit derive formula" 
- re-open the option editor where the user can make changes and re-derive the col again

lets catch up if we need further discussion on how this would work..

**Comment by janagombitova** [comment]
# What is the current status quo? 
Once you set up your transformation and create the new column, for example, the transformation is added to the Transformation log and you see how the data turned out. But what if you made a mistake? Then you need to undo the transformation and start over again. 

Second case: One column holds the most planted vegetables. You have set up a category derive column so you can only show in your visualisation the top 5 and all the other ones bundled into the category 'veggies'. But new submissions just came in and you see that there are new answers that do not fall into the rules you set up and now your visualisation has the top 5, 'veggies' and 'uncategorised'. Now you want to add those new ones to the 'veggies' group too. But not only can you not edit the transformation that handles this, other transformations have been used on the dataset and to undo yours you have to also undo hours of previous work. 

# Opportunity 
The idea is to make it possible to edit a transformation. As other transformations can depend on the one you want to edit, to ensure Lumen does not break and neither the transformations or visualisations depending on it (data type), we would like to make it possible to edit the last transformation. 

Secondly, as with category derived column and score derived column the data type is set by default of the new column, with editing we do not have the risk that following transformations will fail. Thus we want to make it possible to edit a category derived column transformation and a score derived column transformation regardless of its position in the log. 

## Why should we add this? 
- to make it easy to explore data 
- to make it easy to address new data 
- to make it easy to correct mistakes 

## Whose behaviour will change and how? 
Salim, as instead of having to redo a lot of work by undoing and then redoing again, he can just change what he needs. He will also be more conscious of new data coming in but not worry that all his visuals are messed up, as he can address new variables easily. 

## If the change is successful, what might we observe? 
- increase in the use of dataset transformations 
- increase in updating datasets 

## How will this benefit our users? 
It will create a more flexible tool when it comes to data analysis and cleaning while keeping it simple to use. 

## How will this benefit Akvo? 
We hope it will create more internal confidence in using Lumen resulting in more confidence in selling Lumen. 

# Next steps 
We need to discuss implementation
